use super::control_plane::{EpochFence, FencedPeerSignal, OfferAttemptId, OfferEpochFence};
use super::logger;
use super::peer_transport::{rewrite_mdns_candidate_addresses, PeerSignal};
use super::session_gate::{valid_nickname, SessionGate};
use super::types::DirectAddress;
use rand::{distributions::Alphanumeric, Rng};
use std::collections::HashMap;
use std::io::{BufRead, BufReader, Write};
use std::net::{IpAddr, Ipv4Addr, SocketAddr, TcpListener, TcpStream, ToSocketAddrs, UdpSocket};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};
use std::time::Duration;

const DISCOVERY_PORT: u16 = 17424;
const DISCOVERY_MAGIC: &[u8] = b"GOLIVE1";
const MAX_VIEWERS: usize = 8;
const LINE_TIMEOUT: Duration = Duration::from_secs(8);
const PENDING_READ_TIMEOUT: Duration = Duration::from_secs(65);
const ANSWER_WAIT_TIMEOUT: Duration = Duration::from_secs(4);
const STUN_TIMEOUT: Duration = Duration::from_millis(1500);
const STUN_SERVER: (&str, u16) = ("stun.l.google.com", 19302);
type ConnectionWorkers = Arc<Mutex<Vec<JoinHandle<()>>>>;

/// Mints a fresh offer for one Viewer. The id is generated by the TCP
/// handler (it is announced in `PENDING`/`OK` before the offer exists) and
/// the nickname comes from the `NICK` line.
pub(crate) type OfferMint =
    Arc<dyn Fn(&str, &str) -> Result<FencedPeerSignal, String> + Send + Sync>;
type OfferFences = Arc<Mutex<HashMap<String, EpochFence>>>;
type ExactOfferFences = Arc<Mutex<HashMap<String, OfferEpochFence>>>;

enum ProducedOffer {
    Legacy(FencedPeerSignal),
    Exact(ExactOffer),
}

type OfferProducer = Arc<dyn Fn(&str, &str) -> Result<ProducedOffer, String> + Send + Sync>;

fn legacy_offer_producer(mint: OfferMint) -> OfferProducer {
    Arc::new(move |id, nickname| mint(id, nickname).map(ProducedOffer::Legacy))
}

fn exact_offer_producer(mint: ExactOfferMint) -> OfferProducer {
    Arc::new(move |id, nickname| mint(id, nickname).map(ProducedOffer::Exact))
}

/// Exact offer result used by the post-actor integration path. The attempt
/// identity is never reconstructed from a Viewer ID or mailbox drain state.
#[derive(Clone, Debug)]
pub(crate) struct ExactOffer {
    pub(crate) signal: PeerSignal,
    pub(crate) fence: OfferEpochFence,
}

pub(crate) type ExactOfferMint =
    Arc<dyn Fn(&str, &str) -> Result<ExactOffer, String> + Send + Sync>;

#[derive(Clone, Debug)]
pub(crate) struct ExactOfferAnswer {
    pub(crate) signal: PeerSignal,
    pub(crate) fence: OfferEpochFence,
}

/// Redacted one-line summary of an exact offer fence for correlated
/// diagnostics: Session/Share/Link/attempt IDs only. Never includes
/// Passwords, Tokens, SDP payloads, or nicknames.
pub(crate) fn offer_fence_summary(fence: &OfferEpochFence) -> String {
    let link = fence
        .epoch
        .link
        .map(|link| format!("{link:?}"))
        .unwrap_or_else(|| "none".into());
    format!(
        "session={:?} share={:?} link={link} attempt={:?}",
        fence.epoch.session, fence.epoch.share, fence.attempt,
    )
}

#[derive(Clone)]
pub(crate) struct IngressGate {
    active: Arc<AtomicBool>,
}

impl IngressGate {
    pub(crate) fn active() -> Self {
        Self {
            active: Arc::new(AtomicBool::new(true)),
        }
    }

    pub(crate) fn inactive() -> Self {
        Self {
            active: Arc::new(AtomicBool::new(false)),
        }
    }

    pub(crate) fn activate(&self) {
        self.active.store(true, Ordering::Release);
    }

    pub(crate) fn deactivate(&self) {
        self.active.store(false, Ordering::Release);
    }

    pub(crate) fn is_active(&self) -> bool {
        self.active.load(Ordering::Acquire)
    }
}

/// Reports how many Viewers are currently Connected on the engine side, so
/// the room can enforce the 8+8 cap before admitting a new Pending.
pub(crate) type ViewerCount = Arc<dyn Fn() -> usize + Send + Sync>;

pub(crate) struct LanRoom {
    /// Current Room code. Mutable so the Host can rotate it live (PRD-18);
    /// the UDP loop reads it on every discovery request.
    code: Arc<Mutex<String>>,
    pub(crate) port: u16,
    answers: Arc<Mutex<Vec<FencedPeerSignal>>>,
    exact_answers: Arc<Mutex<Vec<ExactOfferAnswer>>>,
    exact_offer_fences: ExactOfferFences,
    shutdown: Arc<AtomicBool>,
    ingress: IngressGate,
    workers: Vec<(&'static str, JoinHandle<()>)>,
    connection_workers: ConnectionWorkers,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ShutdownStatus {
    pub(crate) quiesced: bool,
    pub(crate) pending: Vec<&'static str>,
    pub(crate) errors: Vec<String>,
}

impl LanRoom {
    pub(crate) fn start(
        mint: OfferMint,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
    ) -> Result<Self, String> {
        Self::start_with_producer(
            legacy_offer_producer(mint),
            gate,
            viewer_count,
            host_nickname,
            IngressGate::active(),
        )
    }

    fn start_with_producer(
        producer: OfferProducer,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
        ingress: IngressGate,
    ) -> Result<Self, String> {
        let code = Arc::new(Mutex::new(random_code()));
        let listener = TcpListener::bind("0.0.0.0:0").map_err(|error| error.to_string())?;
        listener
            .set_nonblocking(true)
            .map_err(|error| error.to_string())?;
        let port = listener
            .local_addr()
            .map_err(|error| error.to_string())?
            .port();
        let answers = Arc::new(Mutex::new(Vec::new()));
        let exact_answers = Arc::new(Mutex::new(Vec::new()));
        let offer_fences = Arc::new(Mutex::new(HashMap::new()));
        let exact_offer_fences = Arc::new(Mutex::new(HashMap::new()));
        let connection_workers = Arc::new(Mutex::new(Vec::new()));
        let shutdown = Arc::new(AtomicBool::new(false));
        let tcp_answers = Arc::clone(&answers);
        let tcp_exact_answers = Arc::clone(&exact_answers);
        let tcp_offer_fences = Arc::clone(&offer_fences);
        let tcp_exact_offer_fences = Arc::clone(&exact_offer_fences);
        let tcp_connections = Arc::clone(&connection_workers);
        let tcp_shutdown = Arc::clone(&shutdown);
        let tcp_ingress = ingress.clone();
        let tcp = thread::Builder::new()
            .name("godrinking-room-tcp".into())
            .spawn(move || {
                tcp_loop(
                    listener,
                    producer,
                    gate,
                    viewer_count,
                    tcp_answers,
                    tcp_exact_answers,
                    tcp_offer_fences,
                    tcp_exact_offer_fences,
                    tcp_connections,
                    tcp_shutdown,
                    host_nickname,
                    tcp_ingress,
                )
            })
            .map_err(|error| error.to_string())?;
        let udp_code = Arc::clone(&code);
        let udp_shutdown = Arc::clone(&shutdown);
        let udp_ingress = ingress.clone();
        let udp = thread::Builder::new()
            .name("godrinking-room-udp".into())
            .spawn(move || udp_loop(udp_code, port, udp_shutdown, udp_ingress))
            .map_err(|error| error.to_string())?;
        Ok(Self {
            code,
            port,
            answers,
            exact_answers,
            exact_offer_fences,
            shutdown,
            ingress,
            workers: vec![("LAN TCP worker", tcp), ("LAN UDP worker", udp)],
            connection_workers,
        })
    }

    pub(crate) fn take_answers(&self) -> Vec<FencedPeerSignal> {
        self.answers
            .lock()
            .map(|mut answers| std::mem::take(&mut *answers))
            .unwrap_or_default()
    }

    pub(crate) fn take_exact_answers(&self) -> Vec<ExactOfferAnswer> {
        self.exact_answers
            .lock()
            .map(|mut answers| std::mem::take(&mut *answers))
            .unwrap_or_default()
    }

    /// Creates a non-advertising LAN service for the later actor commit.
    pub(crate) fn start_inactive(
        mint: ExactOfferMint,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
    ) -> Result<Self, String> {
        Self::start_with_producer(
            exact_offer_producer(mint),
            gate,
            viewer_count,
            host_nickname,
            IngressGate::inactive(),
        )
    }

    pub(crate) fn activate(&self) {
        self.ingress.activate();
    }

    pub(crate) fn deactivate(&self) {
        self.ingress.deactivate();
    }

    pub(crate) fn ingress_active(&self) -> bool {
        self.ingress.is_active()
    }

    pub(crate) fn code(&self) -> String {
        self.code
            .lock()
            .map(|code| code.clone())
            .unwrap_or_default()
    }

    pub(crate) fn addresses() -> Vec<String> {
        local_addresses()
    }

    /// Stops LAN discovery/signaling and joins the accept, discovery, and all
    /// accepted-connection workers. Pending connections remain owned for a
    /// later retry instead of being detached and reported as stopped.
    pub(crate) fn shutdown_and_join(&mut self, timeout: Duration) -> ShutdownStatus {
        shutdown_room_workers(
            &self.shutdown,
            &mut self.workers,
            &self.connection_workers,
            timeout,
        )
    }
}

impl Drop for LanRoom {
    fn drop(&mut self) {
        let status = self.shutdown_and_join(Duration::from_secs(3));
        if !status.quiesced {
            eprintln!("[goDrinking] LAN cleanup incomplete: {status:?}");
        }
    }
}

/// Direct join mode: the same GOLIVE2 TCP Signaling as LAN, but with no UDP
/// discovery and no Room code. The Host shares one of the collected
/// addresses (LAN IPv4, public IPv4 via STUN, or global IPv6).
pub(crate) struct DirectRoom {
    pub(crate) port: u16,
    /// True when a NAT port mapping was created (UPnP/NAT-PMP/PCP). Always
    /// false in this fatia; the UI warns that the port must be open.
    pub(crate) mapping: bool,
    answers: Arc<Mutex<Vec<FencedPeerSignal>>>,
    exact_answers: Arc<Mutex<Vec<ExactOfferAnswer>>>,
    exact_offer_fences: ExactOfferFences,
    shutdown: Arc<AtomicBool>,
    ingress: IngressGate,
    addresses: Arc<Mutex<Vec<DirectAddress>>>,
    workers: Vec<(&'static str, JoinHandle<()>)>,
    connection_workers: ConnectionWorkers,
}

impl DirectRoom {
    pub(crate) fn start(
        mint: OfferMint,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
    ) -> Result<Self, String> {
        Self::start_with_producer(
            legacy_offer_producer(mint),
            gate,
            viewer_count,
            host_nickname,
            IngressGate::active(),
        )
    }

    fn start_with_producer(
        producer: OfferProducer,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
        ingress: IngressGate,
    ) -> Result<Self, String> {
        let (listener, ipv6) = bind_direct_listener()?;
        listener
            .set_nonblocking(true)
            .map_err(|error| error.to_string())?;
        let port = listener
            .local_addr()
            .map_err(|error| error.to_string())?
            .port();
        let answers = Arc::new(Mutex::new(Vec::new()));
        let exact_answers = Arc::new(Mutex::new(Vec::new()));
        let offer_fences = Arc::new(Mutex::new(HashMap::new()));
        let exact_offer_fences = Arc::new(Mutex::new(HashMap::new()));
        let connection_workers = Arc::new(Mutex::new(Vec::new()));
        let shutdown = Arc::new(AtomicBool::new(false));
        let addresses = Arc::new(Mutex::new(Vec::new()));
        let tcp_answers = Arc::clone(&answers);
        let tcp_offer_fences = Arc::clone(&offer_fences);
        let tcp_exact_answers = Arc::clone(&exact_answers);
        let tcp_exact_offer_fences = Arc::clone(&exact_offer_fences);
        let tcp_connections = Arc::clone(&connection_workers);
        let tcp_shutdown = Arc::clone(&shutdown);
        let tcp_ingress = ingress.clone();
        let tcp = thread::Builder::new()
            .name("godrinking-direct-tcp".into())
            .spawn(move || {
                tcp_loop(
                    listener,
                    producer,
                    gate,
                    viewer_count,
                    tcp_answers,
                    tcp_exact_answers,
                    tcp_offer_fences,
                    tcp_exact_offer_fences,
                    tcp_connections,
                    tcp_shutdown,
                    host_nickname,
                    tcp_ingress,
                )
            })
            .map_err(|error| error.to_string())?;
        let addr_answers = Arc::clone(&addresses);
        let addr_shutdown = Arc::clone(&shutdown);
        let addr = thread::Builder::new()
            .name("godrinking-direct-addresses".into())
            .spawn(move || address_worker(port, ipv6, addr_answers, addr_shutdown))
            .map_err(|error| error.to_string())?;
        Ok(Self {
            port,
            mapping: false,
            answers,
            exact_answers,
            exact_offer_fences,
            shutdown,
            ingress,
            addresses,
            workers: vec![("Direct TCP worker", tcp), ("Direct address worker", addr)],
            connection_workers,
        })
    }

    pub(crate) fn take_answers(&self) -> Vec<FencedPeerSignal> {
        self.answers
            .lock()
            .map(|mut answers| std::mem::take(&mut *answers))
            .unwrap_or_default()
    }

    pub(crate) fn take_exact_answers(&self) -> Vec<ExactOfferAnswer> {
        self.exact_answers
            .lock()
            .map(|mut answers| std::mem::take(&mut *answers))
            .unwrap_or_default()
    }

    pub(crate) fn start_inactive(
        mint: ExactOfferMint,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
    ) -> Result<Self, String> {
        Self::start_with_producer(
            exact_offer_producer(mint),
            gate,
            viewer_count,
            host_nickname,
            IngressGate::inactive(),
        )
    }

    pub(crate) fn activate(&self) {
        self.ingress.activate();
    }

    pub(crate) fn deactivate(&self) {
        self.ingress.deactivate();
    }

    pub(crate) fn ingress_active(&self) -> bool {
        self.ingress.is_active()
    }

    pub(crate) fn addresses(&self) -> Vec<DirectAddress> {
        self.addresses
            .lock()
            .map(|addresses| addresses.clone())
            .unwrap_or_default()
    }

    /// Stops Direct signaling/address discovery and joins every owned worker.
    pub(crate) fn shutdown_and_join(&mut self, timeout: Duration) -> ShutdownStatus {
        shutdown_room_workers(
            &self.shutdown,
            &mut self.workers,
            &self.connection_workers,
            timeout,
        )
    }
}

impl Drop for DirectRoom {
    fn drop(&mut self) {
        let status = self.shutdown_and_join(Duration::from_secs(3));
        if !status.quiesced {
            eprintln!("[goDrinking] Direct cleanup incomplete: {status:?}");
        }
    }
}

fn shutdown_room_workers(
    shutdown: &Arc<AtomicBool>,
    workers: &mut Vec<(&'static str, JoinHandle<()>)>,
    connection_workers: &ConnectionWorkers,
    timeout: Duration,
) -> ShutdownStatus {
    shutdown.store(true, Ordering::Release);
    let deadline = std::time::Instant::now() + timeout;
    let mut status = ShutdownStatus {
        quiesced: true,
        pending: Vec::new(),
        errors: Vec::new(),
    };
    let owned_workers = std::mem::take(workers);
    for (name, worker) in owned_workers {
        let mut worker = Some(worker);
        join_room_worker(&mut worker, deadline, name, &mut status);
        if let Some(worker) = worker {
            workers.push((name, worker));
        }
    }

    let mut pending_connections = Vec::new();
    if let Ok(mut owned) = connection_workers.lock() {
        pending_connections = std::mem::take(&mut *owned);
    } else {
        status.quiesced = false;
        status
            .errors
            .push("connection worker registry is poisoned".into());
    }
    for worker in pending_connections {
        let mut worker = Some(worker);
        join_room_worker(&mut worker, deadline, "room connection worker", &mut status);
        if let Some(worker) = worker {
            if let Ok(mut owned) = connection_workers.lock() {
                owned.push(worker);
            } else {
                status.quiesced = false;
                status
                    .errors
                    .push("connection worker registry is poisoned".into());
            }
        }
    }
    status
}

fn join_room_worker(
    worker: &mut Option<JoinHandle<()>>,
    deadline: std::time::Instant,
    name: &'static str,
    status: &mut ShutdownStatus,
) {
    let Some(handle) = worker.as_ref() else {
        return;
    };
    while !handle.is_finished() {
        let remaining = deadline.saturating_duration_since(std::time::Instant::now());
        if remaining.is_zero() {
            status.quiesced = false;
            status.pending.push(name);
            return;
        }
        thread::sleep(remaining.min(Duration::from_millis(2)));
    }
    // `is_finished` is checked before join so the bounded path never blocks
    // behind an uncooperative worker.
    let worker = worker.take().expect("room worker handle still present");
    if worker.join().is_err() {
        status.quiesced = false;
        status.errors.push(format!("{name} panicked"));
    }
}

/// Binds the Direct TCP listener. Prefers a dual-stack `[::]:0` socket (one
/// port for IPv4 and IPv6); falls back to `0.0.0.0:0` when the OS binds
/// `[::]` v6-only (Windows) or the bind fails. Returns whether IPv6 is
/// reachable on the chosen listener.
///
/// On Windows `[::]:0` is v6-only by default (IPV6_V6ONLY=1). We try to
/// create a true dual-stack socket via `socket2` with `only_v6(false)` so
/// one port serves both families and the advertised `[ipv6]:port` is
/// actually reachable. Probe + fallback keeps the old behaviour when that
/// fails.
fn bind_direct_listener() -> Result<(TcpListener, bool), String> {
    // Try a true dual-stack socket first (especially on Windows).
    #[cfg(target_os = "windows")]
    {
        if let Ok(listener) = bind_dual_stack() {
            // Dual-stack succeeded: one port for v4 and v6.
            return Ok((listener, true));
        }
    }
    if let Ok(listener) = TcpListener::bind("[::]:0") {
        let port = listener
            .local_addr()
            .map_err(|error| error.to_string())?
            .port();
        // Probe: can IPv4 reach this listener? On Windows `[::]` is v6-only
        // and the probe is refused immediately.
        let ipv4_reachable = TcpStream::connect_timeout(
            &SocketAddr::from(([127, 0, 0, 1], port)),
            Duration::from_millis(150),
        )
        .is_ok();
        if ipv4_reachable {
            logger::log(
                "INFO",
                "direct listen",
                &format!("dual-stack [::]:{port} (v4 reachable)"),
            );
            return Ok((listener, true));
        }
        logger::log(
            "INFO",
            "direct listen",
            &format!("[::]:{port} v6-only, falling back to 0.0.0.0"),
        );
        // Fall through to IPv4-only; the v6-only listener is dropped.
    }
    let listener = TcpListener::bind("0.0.0.0:0").map_err(|error| error.to_string())?;
    logger::log(
        "INFO",
        "direct listen",
        &format!(
            "ipv4-only {}",
            listener.local_addr().map_err(|e| e.to_string())?
        ),
    );
    Ok((listener, false))
}

#[cfg(target_os = "windows")]
fn bind_dual_stack() -> Result<TcpListener, String> {
    use socket2::{Domain, Protocol, Socket, Type};
    let socket =
        Socket::new(Domain::IPV6, Type::STREAM, Some(Protocol::TCP)).map_err(|e| e.to_string())?;
    socket.set_only_v6(false).map_err(|e| e.to_string())?;
    socket.set_nonblocking(false).map_err(|e| e.to_string())?;
    let addr: SocketAddr = "[::]:0"
        .parse()
        .map_err(|e: std::net::AddrParseError| e.to_string())?;
    socket.bind(&addr.into()).map_err(|e| e.to_string())?;
    socket.listen(128).map_err(|e| e.to_string())?;
    let std_listener: std::net::TcpListener = socket.into();
    std_listener
        .set_nonblocking(false)
        .map_err(|e| e.to_string())?;
    Ok(std_listener)
}

/// Collects the copyable Direct addresses on a worker thread so Start never
/// blocks: LAN IPv4 is instant, IPv6 detection is a routing-table lookup, and
/// the STUN binding request is best-effort with a 1.5s timeout. UPnP/NAT-PMP/
/// PCP port mapping is a stub in this fatia (always fails, logged).
fn address_worker(
    port: u16,
    ipv6: bool,
    addresses: Arc<Mutex<Vec<DirectAddress>>>,
    shutdown: Arc<AtomicBool>,
) {
    let mut list = Vec::new();
    if shutdown.load(Ordering::Acquire) {
        return;
    }
    for ip in local_addresses() {
        if let Ok(ip) = ip.parse::<IpAddr>() {
            list.push(direct_entry(ip, port, "lan"));
        }
    }
    if ipv6 {
        if shutdown.load(Ordering::Acquire) {
            return;
        }
        if let Some(ip) = ipv6_global() {
            list.push(direct_entry(ip, port, "ipv6"));
        }
    }
    if let Ok(mut guard) = addresses.lock() {
        *guard = list.clone();
    }
    if shutdown.load(Ordering::Acquire) {
        return;
    }
    if let Some(ip) = stun_public_ipv4() {
        if !list.iter().any(|entry| entry.ip == ip.to_string()) {
            list.push(direct_entry(ip, port, "public"));
        }
        if let Ok(mut guard) = addresses.lock() {
            *guard = list;
        }
    }
    eprintln!("[goDrinking] port mapping failed; Direct over the internet needs this port open");
}

fn direct_entry(ip: IpAddr, port: u16, kind: &str) -> DirectAddress {
    let version = if ip.is_ipv4() { 4 } else { 6 };
    let copy = if ip.is_ipv4() {
        format!("{ip}:{port}")
    } else {
        format!("[{ip}]:{port}")
    };
    DirectAddress {
        ip: ip.to_string(),
        port,
        version,
        kind: kind.into(),
        copy,
    }
}

/// The global IPv6 source address chosen by the routing table, if any.
fn ipv6_global() -> Option<IpAddr> {
    let socket = UdpSocket::bind("[::]:0").ok()?;
    socket.connect("[2600::1]:80").ok()?;
    let ip = socket.local_addr().ok()?.ip();
    match ip {
        IpAddr::V4(v4) if v4.is_loopback() || v4.is_unspecified() => None,
        IpAddr::V6(v6) if v6.is_loopback() || v6.is_unspecified() || v6.is_unicast_link_local() => {
            None
        }
        _ => Some(ip),
    }
}

/// Best-effort STUN binding request to learn the public IPv4. Never blocks
/// Start: it runs on the address worker with a 1.5s socket timeout.
fn stun_public_ipv4() -> Option<IpAddr> {
    let socket = UdpSocket::bind("0.0.0.0:0").ok()?;
    socket.set_read_timeout(Some(STUN_TIMEOUT)).ok()?;
    let mut request = [0_u8; 20];
    request[0..2].copy_from_slice(&0x0001_u16.to_be_bytes()); // binding request
    request[4..8].copy_from_slice(&0x2112_A442_u32.to_be_bytes()); // magic cookie
    let txid: [u8; 12] = rand::random();
    request[8..20].copy_from_slice(&txid);
    let server = STUN_SERVER.to_socket_addrs().ok()?.next()?;
    socket.send_to(&request, server).ok()?;
    let mut response = [0_u8; 512];
    let (size, _) = socket.recv_from(&mut response).ok()?;
    parse_xor_mapped(&response[..size], &txid)
}

/// Parses the XOR-MAPPED-ADDRESS attribute (0x0020) of a STUN binding
/// success response (0x0101) whose transaction id matches.
fn parse_xor_mapped(response: &[u8], txid: &[u8; 12]) -> Option<IpAddr> {
    if response.len() < 20 || response[0..2] != 0x0101_u16.to_be_bytes() || response[8..20] != *txid
    {
        return None;
    }
    let mut offset = 20;
    while offset + 4 <= response.len() {
        let attr_type = u16::from_be_bytes([response[offset], response[offset + 1]]);
        let attr_len = u16::from_be_bytes([response[offset + 2], response[offset + 3]]) as usize;
        let value_start = offset + 4;
        let value_end = (value_start + attr_len).min(response.len());
        if attr_type == 0x0020 && value_end >= value_start + 8 && response[value_start + 1] == 0x01
        {
            let ip = [
                response[value_start + 4] ^ 0x21,
                response[value_start + 5] ^ 0x12,
                response[value_start + 6] ^ 0xA4,
                response[value_start + 7] ^ 0x42,
            ];
            return Some(IpAddr::V4(Ipv4Addr::new(ip[0], ip[1], ip[2], ip[3])));
        }
        offset = value_end + usize::from(attr_len % 4 != 0) * (4 - attr_len % 4);
    }
    None
}

pub(crate) fn random_code() -> String {
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .filter(|byte| byte.is_ascii_alphanumeric() && !byte.is_ascii_lowercase())
        .take(6)
        .map(char::from)
        .collect()
}

fn ice_ip_for_peer(peer: Option<IpAddr>) -> String {
    let Some(ip) = peer else {
        return "127.0.0.1".into();
    };
    let rendered = match ip {
        IpAddr::V4(v4) => v4.to_string(),
        IpAddr::V6(v6) => v6
            .to_ipv4_mapped()
            .map(|v4| v4.to_string())
            .unwrap_or_else(|| v6.to_string()),
    };
    if ip.is_loopback() || local_addresses().iter().any(|local| local == &rendered) {
        return "127.0.0.1".into();
    }
    rendered
}

fn local_addresses() -> Vec<String> {
    let mut addresses = Vec::new();
    if let Ok(socket) = UdpSocket::bind("0.0.0.0:0") {
        let _ = socket.connect("1.1.1.1:80");
        if let Ok(addr) = socket.local_addr() {
            if !addr.ip().is_loopback() {
                addresses.push(addr.ip().to_string());
            }
        }
    }
    if addresses.is_empty() {
        addresses.push("127.0.0.1".into());
    }
    addresses
}

fn tcp_loop(
    listener: TcpListener,
    producer: OfferProducer,
    gate: Arc<SessionGate>,
    viewer_count: ViewerCount,
    answers: Arc<Mutex<Vec<FencedPeerSignal>>>,
    exact_answers: Arc<Mutex<Vec<ExactOfferAnswer>>>,
    offer_fences: OfferFences,
    exact_offer_fences: ExactOfferFences,
    connection_workers: ConnectionWorkers,
    shutdown: Arc<AtomicBool>,
    host_nickname: String,
    ingress: IngressGate,
) {
    while !shutdown.load(Ordering::Acquire) {
        match listener.accept() {
            Ok((stream, _)) => {
                let producer = Arc::clone(&producer);
                let gate = Arc::clone(&gate);
                let viewer_count = Arc::clone(&viewer_count);
                let answers = Arc::clone(&answers);
                let exact_answers = Arc::clone(&exact_answers);
                let offer_fences = Arc::clone(&offer_fences);
                let exact_offer_fences = Arc::clone(&exact_offer_fences);
                let host_nickname = host_nickname.clone();
                let ingress = ingress.clone();
                let connection = thread::Builder::new()
                    .name("godrinking-room-conn".into())
                    .spawn(move || {
                        let _ = handle_tcp_inner(
                            stream,
                            producer,
                            gate,
                            viewer_count,
                            answers,
                            exact_answers,
                            offer_fences,
                            exact_offer_fences,
                            &host_nickname,
                            ingress,
                        );
                    });
                if let Ok(connection) = connection {
                    if let Ok(mut workers) = connection_workers.lock() {
                        workers.push(connection);
                    } else {
                        let _ = connection.join();
                    }
                }
            }
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                thread::sleep(Duration::from_millis(20));
            }
            Err(_) => thread::sleep(Duration::from_millis(50)),
        }
    }
}

/// GOLIVE2 TCP Signaling (PROTOCOL.md section B).
///
/// One TCP per Viewer. The mandatory first line is `HELLO GOLIVE2`; GOLIVE1
/// clients are refused. After `AUTH`/`NICK` the Host either answers
/// `OK <id>` + `OFFER <json>` immediately (Admission off) or `PENDING <id>`
/// and keeps the stream open until the Host decides (Admission on). The
/// Viewer may send `ANSWER <json>` on this same connection after the offer,
/// or on a second connection whose first line is `ANSWER <json>` (the
/// two-step client flow used by the app).
fn handle_tcp(
    stream: TcpStream,
    mint: OfferMint,
    gate: Arc<SessionGate>,
    viewer_count: ViewerCount,
    answers: Arc<Mutex<Vec<FencedPeerSignal>>>,
    host_nickname: &str,
) -> Result<(), String> {
    handle_tcp_inner(
        stream,
        legacy_offer_producer(mint),
        gate,
        viewer_count,
        answers,
        Arc::new(Mutex::new(Vec::new())),
        Arc::new(Mutex::new(HashMap::new())),
        Arc::new(Mutex::new(HashMap::new())),
        host_nickname,
        IngressGate::active(),
    )
}

fn handle_tcp_inner(
    mut stream: TcpStream,
    producer: OfferProducer,
    gate: Arc<SessionGate>,
    viewer_count: ViewerCount,
    answers: Arc<Mutex<Vec<FencedPeerSignal>>>,
    exact_answers: Arc<Mutex<Vec<ExactOfferAnswer>>>,
    offer_fences: OfferFences,
    exact_offer_fences: ExactOfferFences,
    host_nickname: &str,
    ingress: IngressGate,
) -> Result<(), String> {
    stream
        .set_read_timeout(Some(LINE_TIMEOUT))
        .map_err(|error| error.to_string())?;
    let peer_ip = stream.peer_addr().ok().map(|addr| addr.ip());
    logger::log("INFO", "golive2 conn", &format!("peer={peer_ip:?}"));
    let mut reader = BufReader::new(stream.try_clone().map_err(|error| error.to_string())?);

    let mut first = String::new();
    if reader
        .read_line(&mut first)
        .map_err(|error| error.to_string())?
        == 0
    {
        return Err("connection closed before HELLO".into());
    }
    let first = first.trim_end();
    if !ingress.is_active() {
        let _ = stream.write_all(b"ERR RETRY\n");
        return Ok(());
    }
    // Second-connection ANSWER (Fatia 1 flow): no HELLO/AUTH/NICK needed, the
    // offer id inside the JSON matches the Viewer.
    if let Some(json) = first.strip_prefix("ANSWER ") {
        logger::log(
            "INFO",
            "golive2 conn",
            &format!("ANSWER on second connection from {peer_ip:?}"),
        );
        return accept_answer(
            json,
            peer_ip,
            &answers,
            &offer_fences,
            &exact_answers,
            &exact_offer_fences,
        );
    }
    if first != "HELLO GOLIVE2" {
        logger::log(
            "WARN",
            "golive2 conn",
            &format!("expected HELLO GOLIVE2, got {first:?}"),
        );
        let _ = stream.write_all(b"ERR PROTO\n");
        return Err("expected HELLO GOLIVE2".into());
    }

    // Ignore list check before AUTH: a banned IP never gets to NICK.
    if let Some(ip) = peer_ip {
        if gate.is_ignored(ip) {
            logger::log(
                "WARN",
                "golive2 conn",
                &format!("peer {ip} is on the ignore list; refused"),
            );
            let _ = stream.write_all(b"ERR BANNED\n");
            return Err("peer ip is on the ignore list".into());
        }
    }

    let mut auth_line = String::new();
    if reader
        .read_line(&mut auth_line)
        .map_err(|error| error.to_string())?
        == 0
    {
        return Err("connection closed before AUTH".into());
    }
    let auth_line = auth_line.trim_end();
    let offered = match auth_line.strip_prefix("AUTH") {
        Some(rest) => rest.strip_prefix(' ').unwrap_or(""),
        None => {
            logger::log("WARN", "golive2 conn", "expected AUTH line");
            let _ = stream.write_all(b"ERR PROTO\n");
            return Err("expected AUTH line".into());
        }
    };
    if !gate.auth_ok(offered) {
        if let Some(ip) = peer_ip {
            gate.note_auth_failure(ip);
        }
        logger::log(
            "WARN",
            "golive2 conn",
            &format!("AUTH failed (password mismatch) from {peer_ip:?}"),
        );
        let _ = stream.write_all(b"ERR AUTH\n");
        return Err("password mismatch".into());
    }

    let mut nick_line = String::new();
    if reader
        .read_line(&mut nick_line)
        .map_err(|error| error.to_string())?
        == 0
    {
        return Err("connection closed before NICK".into());
    }
    let nick_line = nick_line.trim_end();
    let nickname = match nick_line.strip_prefix("NICK ") {
        Some(nickname) => nickname,
        None => {
            logger::log("WARN", "golive2 conn", "expected NICK line");
            let _ = stream.write_all(b"ERR PROTO\n");
            return Err("expected NICK line".into());
        }
    };
    if !valid_nickname(nickname) {
        logger::log(
            "WARN",
            "golive2 conn",
            &format!("invalid nickname {nickname:?}"),
        );
        let _ = stream.write_all(b"ERR NICK\n");
        return Err("invalid nickname".into());
    }

    if viewer_count() + gate.pending_roster().len() >= MAX_VIEWERS {
        logger::log("WARN", "golive2 conn", "session is full; ERR FULL");
        let _ = stream.write_all(b"ERR FULL\n");
        return Err("session is full".into());
    }

    let id = random_viewer_id();
    if gate.admission() {
        let rx = gate.register_pending(id.clone(), nickname.to_string());
        logger::log(
            "INFO",
            "golive2 conn",
            &format!("PENDING {id} (admission on)"),
        );
        let _ = stream.write_all(format!("PENDING {id}\n").as_bytes());
        if !SessionGate::wait_pending(rx) {
            // Timeout (60s) or Host Reject: remove the slot and tell the
            // Viewer. decide() also removes the slot on timeout.
            gate.decide(&id, false);
            logger::log("INFO", "golive2 conn", &format!("REJECT {id}"));
            let _ = stream.write_all(b"REJECT\n");
            return Ok(());
        }
    }

    let payload = producer(&id, nickname).map_err(|error| {
        logger::log(
            "WARN",
            "golive2 conn",
            &format!("mint failed for {id}: {error}"),
        );
        let _ = stream.write_all(b"ERR FULL\n");
        error
    })?;
    let (signal, legacy_fence, exact_fence) = match payload {
        ProducedOffer::Legacy(payload) => (payload.signal, Some(payload.fence), None),
        ProducedOffer::Exact(payload) => (payload.signal, None, Some(payload.fence)),
    };
    if let Some(fence) = legacy_fence {
        if let Ok(mut fences) = offer_fences.lock() {
            fences.insert(id.clone(), fence);
        }
    }
    if let Some(fence) = exact_fence {
        if let Ok(mut fences) = exact_offer_fences.lock() {
            fences.insert(id.clone(), fence);
        }
    }
    let body = if let Some(fence) = exact_fence {
        serde_json::to_string(&ExactOfferEnvelope {
            signal: signal.clone(),
            fence,
        })
        .map_err(|error| error.to_string())?
    } else {
        serde_json::to_string(&signal).map_err(|error| error.to_string())?
    };
    match exact_fence {
        Some(fence) => logger::log(
            "INFO",
            "golive2 offer",
            &format!("viewer={id} minted {}", offer_fence_summary(&fence)),
        ),
        None => logger::log(
            "INFO",
            "golive2 offer",
            &format!("viewer={id} minted legacy offer"),
        ),
    }
    logger::log("INFO", "golive2 conn", &format!("OK {id} + OFFER"));
    let _ = stream.write_all(format!("OK {id}\n").as_bytes());
    // The Host's Nickname, so the Viewer can label the Session without
    // showing the raw IP:port. Sent before OFFER; old Viewers skip it.
    if !host_nickname.is_empty() {
        let _ = stream.write_all(format!("HOSTNICK {host_nickname}\n").as_bytes());
    }
    let _ = stream.write_all(format!("OFFER {body}\n").as_bytes());

    // The Viewer may answer on this same connection. If it closed the
    // connection instead (two-step flow), the answer arrives on a second
    // connection and is matched by id.
    stream
        .set_read_timeout(Some(ANSWER_WAIT_TIMEOUT))
        .map_err(|error| error.to_string())?;
    let mut answer_line = String::new();
    if reader.read_line(&mut answer_line).is_ok() {
        let answer_line = answer_line.trim_end();
        if let Some(json) = answer_line.strip_prefix("ANSWER ") {
            logger::log(
                "INFO",
                "golive2 conn",
                &format!("ANSWER on first connection from {peer_ip:?}"),
            );
            match (legacy_fence, exact_fence) {
                (Some(fence), None) => {
                    accept_answer_with_fence(json, peer_ip, &answers, fence)?;
                }
                (None, Some(fence)) => {
                    accept_exact_answer_with_fence(
                        json,
                        peer_ip,
                        &exact_answers,
                        &exact_offer_fences,
                        fence,
                    )?;
                }
                _ => return Err("offer producer returned an invalid result".into()),
            }
        }
    }
    Ok(())
}

/// Rejects a stale or unknown answer without side effects: nothing is
/// pushed, no roster or fence state changes. The rejection is logged with
/// the Viewer ID and the reason only — never SDP, Passwords, or Tokens.
fn stale_answer(viewer: &str, detail: &str) -> String {
    logger::log(
        "WARN",
        "golive2 answer",
        &format!("viewer={viewer} dropped stale answer ({detail})"),
    );
    "answer is for a stale or unknown offer".to_owned()
}

fn accept_answer(
    json: &str,
    peer_ip: Option<IpAddr>,
    answers: &Arc<Mutex<Vec<FencedPeerSignal>>>,
    offer_fences: &OfferFences,
    exact_answers: &Arc<Mutex<Vec<ExactOfferAnswer>>>,
    exact_offer_fences: &ExactOfferFences,
) -> Result<(), String> {
    let value: serde_json::Value = serde_json::from_str(json).map_err(|error| error.to_string())?;
    if value.get("fence").is_some() {
        let envelope: ExactAnswerEnvelope =
            serde_json::from_value(value).map_err(|error| error.to_string())?;
        let id = envelope
            .signal
            .id
            .as_ref()
            .ok_or_else(|| "answer is missing viewer id".to_owned())?;
        let expected = exact_offer_fences
            .lock()
            .ok()
            .and_then(|fences| fences.get(id).copied())
            .filter(|fence| *fence == envelope.fence)
            .ok_or_else(|| {
                stale_answer(
                    id,
                    &format!(
                        "fence mismatch current={}",
                        offer_fence_summary(&envelope.fence)
                    ),
                )
            })?;
        return accept_exact_answer_with_fence_signal(
            envelope.signal,
            peer_ip,
            exact_answers,
            expected,
        );
    }
    if let Some(raw_attempt) = value.get("offer_attempt") {
        let attempt: OfferAttemptId =
            serde_json::from_value(raw_attempt.clone()).map_err(|error| error.to_string())?;
        let signal: PeerSignal =
            serde_json::from_value(value).map_err(|error| error.to_string())?;
        let id = signal
            .id
            .clone()
            .ok_or_else(|| "answer is missing viewer id".to_owned())?;
        let fence = exact_offer_fences
            .lock()
            .ok()
            .and_then(|fences| fences.get(&id).copied())
            .filter(|fence| fence.attempt == attempt)
            .ok_or_else(|| stale_answer(&id, &format!("attempt mismatch attempt={attempt:?}")))?;
        return accept_exact_answer_with_fence_signal(signal, peer_ip, exact_answers, fence);
    }
    let mut signal: PeerSignal =
        serde_json::from_value(value).map_err(|error| error.to_string())?;
    let id = signal
        .id
        .clone()
        .ok_or_else(|| "answer is missing viewer id".to_owned())?;
    let fence = offer_fences
        .lock()
        .ok()
        .and_then(|fences| fences.get(&id).copied())
        .ok_or_else(|| {
            logger::log(
                "WARN",
                "golive2 answer",
                &format!("viewer={id} dropped answer (no matching offer)"),
            );
            "answer has no matching offer".to_owned()
        })?;
    accept_answer_with_fence_signal(signal, peer_ip, answers, fence)
}

fn accept_answer_with_fence(
    json: &str,
    peer_ip: Option<IpAddr>,
    answers: &Arc<Mutex<Vec<FencedPeerSignal>>>,
    fence: EpochFence,
) -> Result<(), String> {
    let signal: PeerSignal = serde_json::from_str(json).map_err(|error| error.to_string())?;
    accept_answer_with_fence_signal(signal, peer_ip, answers, fence)
}

fn accept_answer_with_fence_signal(
    mut signal: PeerSignal,
    peer_ip: Option<IpAddr>,
    answers: &Arc<Mutex<Vec<FencedPeerSignal>>>,
    fence: EpochFence,
) -> Result<(), String> {
    signal.sdp = rewrite_mdns_candidate_addresses(&signal.sdp, &ice_ip_for_peer(peer_ip));
    let viewer = signal.id.clone().unwrap_or_default();
    if let Ok(mut answers) = answers.lock() {
        answers.push(FencedPeerSignal { fence, signal });
    }
    logger::log(
        "INFO",
        "golive2 answer",
        &format!("viewer={viewer} accepted legacy answer"),
    );
    Ok(())
}

#[derive(serde::Deserialize, serde::Serialize)]
struct ExactOfferEnvelope {
    #[serde(flatten)]
    signal: PeerSignal,
    fence: OfferEpochFence,
}

#[derive(serde::Deserialize, serde::Serialize)]
struct ExactAnswerEnvelope {
    #[serde(flatten)]
    signal: PeerSignal,
    fence: OfferEpochFence,
}

fn accept_exact_answer_with_fence(
    json: &str,
    peer_ip: Option<IpAddr>,
    answers: &Arc<Mutex<Vec<ExactOfferAnswer>>>,
    offer_fences: &ExactOfferFences,
    expected: OfferEpochFence,
) -> Result<(), String> {
    let signal: PeerSignal = serde_json::from_str(json).map_err(|error| error.to_string())?;
    let id = signal
        .id
        .as_ref()
        .ok_or_else(|| "answer is missing viewer id".to_owned())?;
    if offer_fences
        .lock()
        .ok()
        .map(|fences| fences.get(id).copied() == Some(expected))
        .unwrap_or(false)
    {
        accept_exact_answer_with_fence_signal(signal, peer_ip, answers, expected)
    } else {
        Err("answer is for a stale or unknown offer".into())
    }
}

fn accept_exact_answer_with_fence_signal(
    mut signal: PeerSignal,
    peer_ip: Option<IpAddr>,
    answers: &Arc<Mutex<Vec<ExactOfferAnswer>>>,
    fence: OfferEpochFence,
) -> Result<(), String> {
    signal.sdp = rewrite_mdns_candidate_addresses(&signal.sdp, &ice_ip_for_peer(peer_ip));
    let viewer = signal.id.clone().unwrap_or_default();
    if let Ok(mut answers) = answers.lock() {
        answers.push(ExactOfferAnswer { fence, signal });
    }
    logger::log(
        "INFO",
        "golive2 answer",
        &format!("viewer={viewer} accepted {}", offer_fence_summary(&fence)),
    );
    Ok(())
}

fn random_viewer_id() -> String {
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .filter(|byte| byte.is_ascii_alphanumeric() && !byte.is_ascii_lowercase())
        .take(8)
        .map(char::from)
        .collect()
}

fn udp_loop(
    code: Arc<Mutex<String>>,
    tcp_port: u16,
    shutdown: Arc<AtomicBool>,
    ingress: IngressGate,
) {
    let Ok(socket) = UdpSocket::bind(("0.0.0.0", DISCOVERY_PORT)) else {
        return;
    };
    let _ = socket.set_read_timeout(Some(Duration::from_millis(200)));
    let mut buffer = [0_u8; 256];
    while !shutdown.load(Ordering::Acquire) {
        let Ok((size, from)) = socket.recv_from(&mut buffer) else {
            continue;
        };
        let request = String::from_utf8_lossy(&buffer[..size]);
        if !ingress.is_active() {
            continue;
        }
        let current = code.lock().map(|code| code.clone()).unwrap_or_default();
        if let Some(reply) = udp_reply(&request, &current, tcp_port) {
            let _ = socket.send_to(reply.as_bytes(), from);
        }
    }
}

/// Matches a `GOLIVE1 FIND <code>` discovery request against the current
/// Room code. Returns the `GOLIVE1 HOST <code> <port>` reply, or None.
fn udp_reply(request: &str, code: &str, tcp_port: u16) -> Option<String> {
    let mut parts = request.split_whitespace();
    if parts.next() != Some(std::str::from_utf8(DISCOVERY_MAGIC).unwrap_or("GOLIVE1")) {
        return None;
    }
    if parts.next() != Some("FIND") {
        return None;
    }
    if parts.next() != Some(code) {
        return None;
    }
    Some(format!("GOLIVE1 HOST {code} {tcp_port}"))
}

pub fn discover_room(
    code: &str,
    password: &str,
    nickname: &str,
) -> Result<(SocketAddr, PeerSignal, String), String> {
    let host = discover_host(code, nickname)?;
    let (offer, host_nickname) = fetch_offer(host, password, nickname)?;
    Ok((host, offer, host_nickname))
}

fn discover_host(code: &str, nickname: &str) -> Result<SocketAddr, String> {
    logger::begin_session("viewer", "lan");
    logger::log(
        "INFO",
        "lan find",
        &format!("code={code} nickname={nickname}"),
    );
    let socket = UdpSocket::bind("0.0.0.0:0").map_err(|error| error.to_string())?;
    socket
        .set_broadcast(true)
        .map_err(|error| error.to_string())?;
    socket
        .set_read_timeout(Some(Duration::from_secs(2)))
        .map_err(|error| error.to_string())?;
    let query = format!("GOLIVE1 FIND {code}");
    socket
        .send_to(query.as_bytes(), ("255.255.255.255", DISCOVERY_PORT))
        .map_err(|error| {
            logger::log("ERROR", "lan find", &format!("broadcast failed: {error}"));
            error.to_string()
        })?;
    let mut buffer = [0_u8; 256];
    let (size, from) = socket.recv_from(&mut buffer).map_err(|_| {
        logger::log(
            "ERROR",
            "lan find",
            "no host answered (room not found on this network)",
        );
        "room was not found on this network".to_owned()
    })?;
    let reply = String::from_utf8_lossy(&buffer[..size]);
    let mut parts = reply.split_whitespace();
    if parts.next() != Some("GOLIVE1") || parts.next() != Some("HOST") {
        logger::log("ERROR", "lan find", &format!("invalid reply: {reply}"));
        return Err("invalid room discovery reply".into());
    }
    if parts.next() != Some(code) {
        logger::log(
            "ERROR",
            "lan find",
            &format!("code mismatch in reply: {reply}"),
        );
        return Err("room code mismatch".into());
    }
    let port = parts
        .next()
        .and_then(|value| value.parse::<u16>().ok())
        .ok_or_else(|| {
            logger::log("ERROR", "lan find", &format!("reply missing port: {reply}"));
            "room reply is missing a port".to_owned()
        })?;
    let host = SocketAddr::new(from.ip(), port);
    logger::log("INFO", "lan find", &format!("host found at {host}"));
    Ok(host)
}

/// Exact-fence LAN discovery for the post-actor integration path.
pub(crate) fn discover_room_exact(
    code: &str,
    password: &str,
    nickname: &str,
) -> Result<(SocketAddr, ExactOffer, String), String> {
    let host = discover_host(code, nickname)?;
    let (offer, host_nickname) = fetch_offer_exact(host, password, nickname)?;
    Ok((host, offer, host_nickname))
}

/// GOLIVE2 Viewer handshake: `HELLO GOLIVE2` / `AUTH` / `NICK`, then wait for
/// `OK`/`PENDING` and finally `OFFER <json>`. With Admission on the Host may
/// keep us waiting up to 60s before deciding; the stream stays open. Returns
/// the offer plus the Host's Nickname (empty when the Host sent none).
pub(crate) fn fetch_offer(
    host: SocketAddr,
    password: &str,
    nickname: &str,
) -> Result<(PeerSignal, String), String> {
    let (signal, _, host_nickname) = fetch_offer_with_identity(host, password, nickname)?;
    Ok((signal, host_nickname))
}

pub(crate) fn fetch_offer_exact(
    host: SocketAddr,
    password: &str,
    nickname: &str,
) -> Result<(ExactOffer, String), String> {
    let (signal, fence, host_nickname) = fetch_offer_with_identity(host, password, nickname)?;
    let fence =
        fence.ok_or_else(|| "host returned a legacy offer without an exact fence".to_owned())?;
    Ok((ExactOffer { signal, fence }, host_nickname))
}

fn fetch_offer_with_identity(
    host: SocketAddr,
    password: &str,
    nickname: &str,
) -> Result<(PeerSignal, Option<OfferEpochFence>, String), String> {
    logger::log("INFO", "golive2", &format!("connect {host}"));
    let mut stream = TcpStream::connect_timeout(&host, Duration::from_secs(8))
        .map_err(|error| format!("connect: {error}"))?;
    stream
        .set_read_timeout(Some(PENDING_READ_TIMEOUT))
        .map_err(|error| error.to_string())?;
    stream
        .write_all(b"HELLO GOLIVE2\n")
        .map_err(|error| error.to_string())?;
    if password.is_empty() {
        stream
            .write_all(b"AUTH\n")
            .map_err(|error| error.to_string())?;
    } else {
        stream
            .write_all(format!("AUTH {password}\n").as_bytes())
            .map_err(|error| error.to_string())?;
    }
    stream
        .write_all(format!("NICK {nickname}\n").as_bytes())
        .map_err(|error| error.to_string())?;
    logger::log("INFO", "golive2", "sent HELLO GOLIVE2 / AUTH / NICK");
    let mut reader = BufReader::new(stream);
    let mut host_nickname = String::new();
    loop {
        let mut line = String::new();
        if reader
            .read_line(&mut line)
            .map_err(|error| error.to_string())?
            == 0
        {
            logger::log("WARN", "golive2", "host closed the connection");
            return Err("host closed the connection".into());
        }
        let line = line.trim_end();
        if let Some(json) = line.strip_prefix("OFFER ") {
            logger::log("INFO", "golive2", "received OFFER");
            if let Ok(envelope) = serde_json::from_str::<ExactOfferEnvelope>(json) {
                return Ok((envelope.signal, Some(envelope.fence), host_nickname));
            }
            let signal = serde_json::from_str(json).map_err(|error| error.to_string())?;
            return Ok((signal, None, host_nickname));
        }
        if let Some(name) = line.strip_prefix("HOSTNICK ") {
            host_nickname = name.to_owned();
            continue;
        }
        if line == "REJECT" {
            logger::log("WARN", "golive2", "received REJECT (host declined)");
            return Err("The host declined.".into());
        }
        if line == "PENDING" || line.starts_with("PENDING ") {
            logger::log("INFO", "golive2", "received PENDING (waiting for the host)");
            continue;
        }
        if line == "OK" || line.starts_with("OK ") {
            logger::log("INFO", "golive2", "received OK");
            continue;
        }
        if let Some(error) = line.strip_prefix("ERR ") {
            return Err(protocol_error(error));
        }
    }
}

/// Direct join: no UDP discovery, straight GOLIVE2 TCP to the address the
/// Host shared. TCP failures map to the UI string of UI.md.
pub fn discover_direct(
    host: SocketAddr,
    password: &str,
    nickname: &str,
) -> Result<(PeerSignal, String), String> {
    logger::begin_session("viewer", "direct");
    logger::log(
        "INFO",
        "direct connect",
        &format!("host={host} nickname={nickname}"),
    );
    fetch_offer(host, password, nickname).map_err(|error| {
        if error.starts_with("connect: ") {
            logger::log("ERROR", "direct connect", &error);
            "Could not reach that address.".into()
        } else {
            error
        }
    })
}

pub(crate) fn discover_direct_exact(
    host: SocketAddr,
    password: &str,
    nickname: &str,
) -> Result<(ExactOffer, String), String> {
    logger::begin_session("viewer", "direct");
    logger::log(
        "INFO",
        "direct connect",
        &format!("host={host} nickname={nickname}"),
    );
    fetch_offer_exact(host, password, nickname).map_err(|error| {
        if error.starts_with("connect: ") {
            logger::log("ERROR", "direct connect", &error);
            "Could not reach that address.".into()
        } else {
            error
        }
    })
}

/// Maps `ERR *` lines to the generic UI strings of UI.md: wrong Password and
/// unknown rooms are indistinguishable, and a banned IP gets the same answer.
/// The raw code is logged so the UI string can be traced.
fn protocol_error(code: &str) -> String {
    logger::log("ERROR", "golive2 err", &format!("ERR {code}"));
    match code {
        "FULL" => "This session is full.".into(),
        _ => "Could not join.".into(),
    }
}

pub fn submit_answer(host: SocketAddr, answer: &PeerSignal) -> Result<(), String> {
    let mut stream = TcpStream::connect_timeout(&host, Duration::from_secs(3))
        .map_err(|error| error.to_string())?;
    let body = serde_json::to_string(answer).map_err(|error| error.to_string())?;
    stream
        .write_all(format!("ANSWER {body}\n").as_bytes())
        .map_err(|error| error.to_string())?;
    stream.shutdown(std::net::Shutdown::Write).ok();
    Ok(())
}

pub(crate) fn submit_answer_exact(
    host: SocketAddr,
    answer: &PeerSignal,
    fence: OfferEpochFence,
) -> Result<(), String> {
    let mut stream = TcpStream::connect_timeout(&host, Duration::from_secs(3))
        .map_err(|error| error.to_string())?;
    let body = serde_json::to_string(&ExactAnswerEnvelope {
        signal: answer.clone(),
        fence,
    })
    .map_err(|error| error.to_string())?;
    stream
        .write_all(format!("ANSWER {body}\n").as_bytes())
        .map_err(|error| error.to_string())?;
    stream.shutdown(std::net::Shutdown::Write).ok();
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        accept_answer, handle_tcp, handle_tcp_inner, offer_fence_summary, random_code, udp_reply,
        ExactAnswerEnvelope, ExactOfferFences, IngressGate, OfferFences, OfferMint, OfferProducer,
        ViewerCount,
    };
    use crate::media::control_plane::{
        EpochFence, LinkId, OfferEpochFence, SessionEpoch, ShareEpoch,
    };
    use crate::media::peer_transport::{PeerSignal, PeerSignalKind};
    use crate::media::session_gate::SessionGate;
    use std::io::{BufRead, BufReader, Write};
    use std::net::{TcpListener, TcpStream};
    use std::sync::{Arc, Mutex};
    use std::time::Duration;

    fn test_mint() -> OfferMint {
        Arc::new(|_id, _nickname| {
            Ok(super::FencedPeerSignal {
                fence: EpochFence {
                    session: SessionEpoch(1),
                    share: ShareEpoch(1),
                    link: None,
                },
                signal: PeerSignal {
                    kind: PeerSignalKind::Offer,
                    sdp: "v=0\r\n".into(),
                    id: Some("abcd1234".into()),
                },
            })
        })
    }

    fn test_count() -> ViewerCount {
        Arc::new(|| 0)
    }

    fn test_fence(attempt: u64) -> OfferEpochFence {
        OfferEpochFence {
            epoch: EpochFence {
                session: SessionEpoch(1),
                share: ShareEpoch(2),
                link: Some(LinkId(3)),
            },
            attempt: serde_json::from_value(serde_json::json!(attempt)).expect("attempt"),
        }
    }

    fn answer_signal(id: &str) -> PeerSignal {
        PeerSignal {
            kind: PeerSignalKind::Answer,
            sdp: "v=0\r\n".into(),
            id: Some(id.into()),
        }
    }

    fn envelope_json(id: &str, fence: OfferEpochFence) -> String {
        serde_json::to_string(&ExactAnswerEnvelope {
            signal: answer_signal(id),
            fence,
        })
        .expect("json")
    }

    fn answer_fixtures() -> (
        std::sync::Arc<std::sync::Mutex<Vec<super::FencedPeerSignal>>>,
        std::sync::Arc<std::sync::Mutex<Vec<super::ExactOfferAnswer>>>,
        OfferFences,
        ExactOfferFences,
    ) {
        (
            Arc::new(Mutex::new(Vec::new())),
            Arc::new(Mutex::new(Vec::new())),
            Arc::new(Mutex::new(std::collections::HashMap::new())),
            Arc::new(Mutex::new(std::collections::HashMap::new())),
        )
    }

    #[test]
    fn room_codes_are_short_and_uppercase() {
        let code = random_code();
        assert_eq!(code.len(), 6);
        assert!(code.chars().all(|ch| ch.is_ascii_alphanumeric()));
        assert_eq!(code, code.to_ascii_uppercase());
    }

    #[test]
    fn udp_discovery_answers_only_the_current_code() {
        // Old code stops resolving after a rotate; the new one answers.
        assert_eq!(
            udp_reply("GOLIVE1 FIND ABC123", "ABC123", 41234).as_deref(),
            Some("GOLIVE1 HOST ABC123 41234")
        );
        assert_eq!(udp_reply("GOLIVE1 FIND ABC123", "XYZ789", 41234), None);
        assert_eq!(
            udp_reply("GOLIVE1 FIND XYZ789", "XYZ789", 41234).as_deref(),
            Some("GOLIVE1 HOST XYZ789 41234")
        );
        assert_eq!(
            udp_reply("GOLIVE1 FIND ABC123", "ABC123", 41234).as_deref(),
            Some("GOLIVE1 HOST ABC123 41234")
        );
        // Garbage and wrong magic are ignored.
        assert_eq!(udp_reply("GOLIVE2 FIND ABC123", "ABC123", 41234), None);
        assert_eq!(udp_reply("GOLIVE1 LOOK ABC123", "ABC123", 41234), None);
    }

    #[test]
    fn inactive_ingress_is_quiet_until_activation() {
        let gate = IngressGate::inactive();
        assert!(!gate.is_active());
        gate.activate();
        assert!(gate.is_active());
        gate.deactivate();
        assert!(!gate.is_active());
    }

    #[test]
    fn delayed_exact_answer_for_replaced_offer_is_rejected() {
        let answers = Arc::new(Mutex::new(Vec::new()));
        let exact_answers = Arc::new(Mutex::new(Vec::new()));
        let legacy_fences: OfferFences = Arc::new(Mutex::new(std::collections::HashMap::new()));
        let exact_fences: ExactOfferFences = Arc::new(Mutex::new(std::collections::HashMap::new()));
        let current = test_fence(2);
        exact_fences
            .lock()
            .expect("fences")
            .insert("abcd1234".into(), current);
        let stale = ExactAnswerEnvelope {
            signal: PeerSignal {
                kind: PeerSignalKind::Answer,
                sdp: "v=0\r\n".into(),
                id: Some("abcd1234".into()),
            },
            fence: test_fence(1),
        };
        let result = accept_answer(
            &serde_json::to_string(&stale).expect("json"),
            None,
            &answers,
            &legacy_fences,
            &exact_answers,
            &exact_fences,
        );
        assert!(result.is_err());
        assert!(exact_answers.lock().expect("answers").is_empty());
    }

    #[test]
    fn fence_summary_carries_ids_without_secrets() {
        let summary = offer_fence_summary(&test_fence(7));
        assert!(summary.contains("session="));
        assert!(summary.contains("share="));
        assert!(summary.contains("link="));
        assert!(summary.contains("attempt="));
        assert!(!summary.contains("v=0"));
    }

    #[test]
    fn replacement_link_rejects_stale_answer_without_side_effects() {
        let (answers, exact_answers, legacy_fences, exact_fences) = answer_fixtures();
        // Link replacement: the Viewer was re-offered (attempt 2). A delayed
        // answer to attempt 1 must be dropped with no side effects.
        exact_fences
            .lock()
            .expect("fences")
            .insert("abcd1234".into(), test_fence(2));
        let result = accept_answer(
            &envelope_json("abcd1234", test_fence(1)),
            None,
            &answers,
            &legacy_fences,
            &exact_answers,
            &exact_fences,
        );
        assert!(result.is_err());
        assert!(exact_answers.lock().expect("answers").is_empty());
        assert!(answers.lock().expect("answers").is_empty());
        // The current attempt is still accepted on the replacement link.
        let result = accept_answer(
            &envelope_json("abcd1234", test_fence(2)),
            None,
            &answers,
            &legacy_fences,
            &exact_answers,
            &exact_fences,
        );
        assert!(result.is_ok());
        let stored = exact_answers.lock().expect("answers");
        assert_eq!(stored.len(), 1);
        assert_eq!(stored[0].fence, test_fence(2));
        assert_eq!(stored[0].signal.id.as_deref(), Some("abcd1234"));
    }

    #[test]
    fn late_join_after_share_replacement_uses_current_fence() {
        let (answers, exact_answers, legacy_fences, exact_fences) = answer_fixtures();
        // Share restart moved share 2 -> 3; the late answer to the old Share
        // must be rejected while the fresh Share's answer is accepted.
        let old_share = OfferEpochFence {
            epoch: EpochFence {
                session: SessionEpoch(1),
                share: ShareEpoch(2),
                link: Some(LinkId(3)),
            },
            attempt: serde_json::from_value(serde_json::json!(1)).expect("attempt"),
        };
        let new_share = OfferEpochFence {
            epoch: EpochFence {
                session: SessionEpoch(1),
                share: ShareEpoch(3),
                link: Some(LinkId(4)),
            },
            attempt: serde_json::from_value(serde_json::json!(9)).expect("attempt"),
        };
        exact_fences
            .lock()
            .expect("fences")
            .insert("latejoin".into(), new_share);
        assert!(accept_answer(
            &envelope_json("latejoin", old_share),
            None,
            &answers,
            &legacy_fences,
            &exact_answers,
            &exact_fences,
        )
        .is_err());
        assert!(exact_answers.lock().expect("answers").is_empty());
        assert!(accept_answer(
            &envelope_json("latejoin", new_share),
            None,
            &answers,
            &legacy_fences,
            &exact_answers,
            &exact_fences,
        )
        .is_ok());
        let stored = exact_answers.lock().expect("answers");
        assert_eq!(stored.len(), 1);
        assert_eq!(stored[0].fence, new_share);
    }

    #[test]
    fn one_viewer_failure_does_not_stop_others() {
        let (answers, exact_answers, legacy_fences, exact_fences) = answer_fixtures();
        {
            let mut fences = exact_fences.lock().expect("fences");
            fences.insert("goodview".into(), test_fence(5));
            fences.insert("badviewx".into(), test_fence(6));
        }
        // badviewx answers with the wrong attempt: rejected, no side effects.
        assert!(accept_answer(
            &envelope_json("badviewx", test_fence(1)),
            None,
            &answers,
            &legacy_fences,
            &exact_answers,
            &exact_fences,
        )
        .is_err());
        // goodview's exact answer on the same drain is still accepted.
        assert!(accept_answer(
            &envelope_json("goodview", test_fence(5)),
            None,
            &answers,
            &legacy_fences,
            &exact_answers,
            &exact_fences,
        )
        .is_ok());
        let stored = exact_answers.lock().expect("answers");
        assert_eq!(stored.len(), 1);
        assert_eq!(stored[0].signal.id.as_deref(), Some("goodview"));
    }

    #[test]
    fn inactive_ingress_refuses_hello_until_actor_commit() {
        // Join-service ingress stays unpublished until the actor commits:
        // HELLO gets ERR RETRY and the offer producer is never called.
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), false));
        let minted = Arc::new(std::sync::atomic::AtomicBool::new(false));
        let minted_flag = Arc::clone(&minted);
        let producer: OfferProducer = Arc::new(move |_id, _nickname| {
            minted_flag.store(true, std::sync::atomic::Ordering::Release);
            Err("must not mint before commit".into())
        });
        let ingress = IngressGate::inactive();
        let server_ingress = ingress.clone();
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp_inner(
                stream,
                producer,
                gate,
                test_count(),
                Arc::new(Mutex::new(Vec::new())),
                Arc::new(Mutex::new(Vec::new())),
                Arc::new(Mutex::new(std::collections::HashMap::new())),
                Arc::new(Mutex::new(std::collections::HashMap::new())),
                "Host",
                server_ingress,
            )
        });
        let mut client =
            TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client.write_all(b"HELLO GOLIVE2\n").expect("write");
        let mut reader = BufReader::new(client.try_clone().expect("clone"));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read retry");
        assert_eq!(line.trim(), "ERR RETRY");
        drop(reader);
        drop(client);
        server.join().expect("join").expect("handle");
        assert!(
            !minted.load(std::sync::atomic::Ordering::Acquire),
            "precommit worker must stay inert"
        );
        // Actor commit publishes the join service.
        ingress.activate();
        assert!(ingress.is_active());
    }

    #[test]
    fn get_offer_mints_a_fresh_signal() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), false));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server_answers = Arc::clone(&answers);
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(
                stream,
                test_mint(),
                gate,
                test_count(),
                server_answers,
                "Host",
            )
        });
        let mut client =
            TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH\nNICK Ana\n")
            .expect("write");
        let mut reader = BufReader::new(client.try_clone().expect("clone"));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read ok");
        assert!(line.starts_with("OK "));
        let mut line = String::new();
        loop {
            reader.read_line(&mut line).expect("read offer");
            if line.starts_with("OFFER ") {
                break;
            }
            line.clear();
        }
        assert!(line.contains("abcd1234"));
        // Same-connection ANSWER is accepted and pushed to the answers Vec.
        client
            .write_all(b"ANSWER {\"type\":\"answer\",\"sdp\":\"v=0\\r\\n\",\"id\":\"abcd1234\"}\n")
            .expect("write answer");
        server.join().expect("join").expect("handle");
        let answers = answers.lock().expect("answers");
        assert_eq!(answers.len(), 1);
        assert_eq!(answers[0].signal.id.as_deref(), Some("abcd1234"));
    }

    #[test]
    fn wrong_password_gets_err_auth() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new("secret".into(), false));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(stream, test_mint(), gate, test_count(), answers, "Host")
        });
        let mut client =
            TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH wrong\nNICK Ana\n")
            .expect("write");
        let mut body = String::new();
        use std::io::Read;
        client.read_to_string(&mut body).expect("read");
        assert!(body.starts_with("ERR AUTH"));
        let _ = server.join().expect("join");
    }

    #[test]
    fn golive1_get_offer_is_refused() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), false));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(stream, test_mint(), gate, test_count(), answers, "Host")
        });
        let mut client =
            TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client.write_all(b"GET_OFFER\n").expect("write");
        let mut body = String::new();
        use std::io::Read;
        client.read_to_string(&mut body).expect("read");
        assert!(body.starts_with("ERR PROTO"));
        let _ = server.join().expect("join");
    }

    #[test]
    fn admission_pending_then_accept_sends_offer() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), true));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server_gate = Arc::clone(&gate);
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(
                stream,
                test_mint(),
                server_gate,
                test_count(),
                answers,
                "Host",
            )
        });
        let mut client =
            TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH\nNICK Joao\n")
            .expect("write");
        let mut reader = BufReader::new(client.try_clone().expect("clone"));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read pending");
        let id = line
            .strip_prefix("PENDING ")
            .expect("pending line")
            .trim()
            .to_owned();
        assert!(!id.is_empty());
        // The Host decides from another thread; the pending TCP stays open.
        assert!(gate.decide(&id, true));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read ok");
        assert!(line.starts_with("OK "));
        let mut line = String::new();
        loop {
            reader.read_line(&mut line).expect("read offer");
            if line.starts_with("OFFER ") {
                break;
            }
            line.clear();
        }
        assert!(line.starts_with("OFFER "));
        drop(reader);
        drop(client);
        server.join().expect("join").expect("handle");
    }

    #[test]
    fn admission_reject_closes_with_reject() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), true));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server_gate = Arc::clone(&gate);
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(
                stream,
                test_mint(),
                server_gate,
                test_count(),
                answers,
                "Host",
            )
        });
        let mut client =
            TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH\nNICK Joao\n")
            .expect("write");
        let mut reader = BufReader::new(client.try_clone().expect("clone"));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read pending");
        let id = line
            .strip_prefix("PENDING ")
            .expect("pending line")
            .trim()
            .to_owned();
        assert!(gate.decide(&id, false));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read reject");
        assert_eq!(line.trim(), "REJECT");
        drop(reader);
        drop(client);
        server.join().expect("join").expect("handle");
    }

    #[test]
    fn stun_xor_mapped_address_parses() {
        use super::parse_xor_mapped;
        let txid = [7_u8; 12];
        // Binding success header + XOR-MAPPED-ADDRESS for 203.0.113.9:41234.
        let mut response = Vec::new();
        response.extend_from_slice(&0x0101_u16.to_be_bytes());
        response.extend_from_slice(&0x0008_u16.to_be_bytes());
        response.extend_from_slice(&0x2112_A442_u32.to_be_bytes());
        response.extend_from_slice(&txid);
        response.extend_from_slice(&0x0020_u16.to_be_bytes());
        response.extend_from_slice(&0x0008_u16.to_be_bytes());
        response.push(0);
        response.push(0x01); // IPv4 family
        response.extend_from_slice(&(41234_u16 ^ 0x2112).to_be_bytes());
        response.extend_from_slice(&[203 ^ 0x21, 0 ^ 0x12, 113 ^ 0xA4, 9 ^ 0x42]);
        let parsed = parse_xor_mapped(&response, &txid).expect("parses");
        assert_eq!(parsed.to_string(), "203.0.113.9");
        // Wrong transaction id is rejected.
        assert!(parse_xor_mapped(&response, &[1_u8; 12]).is_none());
    }

    #[test]
    fn shutdown_reports_pending_room_worker_without_detaching_it() {
        let shutdown = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
        let connections = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
        let mut workers = vec![(
            "LAN TCP worker",
            std::thread::spawn(|| {
                std::thread::sleep(Duration::from_millis(20));
            }),
        )];
        let status = super::shutdown_room_workers(
            &shutdown,
            &mut workers,
            &connections,
            Duration::from_millis(1),
        );
        assert!(!status.quiesced);
        assert_eq!(status.pending, vec!["LAN TCP worker"]);
        assert_eq!(workers.len(), 1);
        let status = super::shutdown_room_workers(
            &shutdown,
            &mut workers,
            &connections,
            Duration::from_secs(1),
        );
        assert!(status.quiesced, "room shutdown status: {status:?}");
        assert!(workers.is_empty());
    }
}
