use super::logger;
use super::peer_transport::{rewrite_mdns_candidate_addresses, PeerSignal};
use super::session_gate::{valid_nickname, SessionGate};
use super::types::DirectAddress;
use rand::{distributions::Alphanumeric, Rng};
use std::io::{BufRead, BufReader, Write};
use std::net::{IpAddr, Ipv4Addr, SocketAddr, TcpListener, TcpStream, ToSocketAddrs, UdpSocket};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};
use std::time::Duration;

const DISCOVERY_PORT: u16 = 17424;
const DISCOVERY_MAGIC: &[u8] = b"GOLIVE1";
const MAX_VIEWERS: usize = 8;
const LINE_TIMEOUT: Duration = Duration::from_secs(8);
const PENDING_READ_TIMEOUT: Duration = Duration::from_secs(65);
const ANSWER_WAIT_TIMEOUT: Duration = Duration::from_secs(4);
const STUN_TIMEOUT: Duration = Duration::from_millis(1500);
const STUN_SERVER: (&str, u16) = ("stun.l.google.com", 19302);

/// Mints a fresh offer for one Viewer. The id is generated by the TCP
/// handler (it is announced in `PENDING`/`OK` before the offer exists) and
/// the nickname comes from the `NICK` line.
pub(crate) type OfferMint = Arc<dyn Fn(&str, &str) -> Result<PeerSignal, String> + Send + Sync>;

/// Reports how many Viewers are currently Connected on the engine side, so
/// the room can enforce the 8+8 cap before admitting a new Pending.
pub(crate) type ViewerCount = Arc<dyn Fn() -> usize + Send + Sync>;

pub(crate) struct LanRoom {
    /// Current Room code. Mutable so the Host can rotate it live (PRD-18);
    /// the UDP loop reads it on every discovery request.
    code: Arc<Mutex<String>>,
    pub(crate) port: u16,
    answers: Arc<Mutex<Vec<PeerSignal>>>,
    shutdown: Arc<AtomicBool>,
    _workers: Vec<JoinHandle<()>>,
}

impl LanRoom {
    pub(crate) fn start(
        mint: OfferMint,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
    ) -> Result<Self, String> {
        let code = Arc::new(Mutex::new(random_code()));
        let listener = TcpListener::bind("0.0.0.0:0").map_err(|error| error.to_string())?;
        listener
            .set_nonblocking(true)
            .map_err(|error| error.to_string())?;
        let port = listener.local_addr().map_err(|error| error.to_string())?.port();
        let answers = Arc::new(Mutex::new(Vec::new()));
        let shutdown = Arc::new(AtomicBool::new(false));
        let tcp_answers = Arc::clone(&answers);
        let tcp_shutdown = Arc::clone(&shutdown);
        let tcp = thread::Builder::new()
            .name("godrinking-room-tcp".into())
            .spawn(move || {
                tcp_loop(
                    listener,
                    mint,
                    gate,
                    viewer_count,
                    tcp_answers,
                    tcp_shutdown,
                    host_nickname,
                )
            })
            .map_err(|error| error.to_string())?;
        let udp_code = Arc::clone(&code);
        let udp_shutdown = Arc::clone(&shutdown);
        let udp = thread::Builder::new()
            .name("godrinking-room-udp".into())
            .spawn(move || udp_loop(udp_code, port, udp_shutdown))
            .map_err(|error| error.to_string())?;
        Ok(Self {
            code,
            port,
            answers,
            shutdown,
            _workers: vec![tcp, udp],
        })
    }

    pub(crate) fn take_answers(&self) -> Vec<PeerSignal> {
        self.answers
            .lock()
            .map(|mut answers| std::mem::take(&mut *answers))
            .unwrap_or_default()
    }

    pub(crate) fn code(&self) -> String {
        self.code
            .lock()
            .map(|code| code.clone())
            .unwrap_or_default()
    }

    pub(crate) fn addresses() -> Vec<String> {
        local_addresses()
    }
}

impl Drop for LanRoom {
    fn drop(&mut self) {
        self.shutdown.store(true, Ordering::Release);
    }
}

/// Direct join mode: the same GOLIVE2 TCP Signaling as LAN, but with no UDP
/// discovery and no Room code. The Host shares one of the collected
/// addresses (LAN IPv4, public IPv4 via STUN, or global IPv6).
pub(crate) struct DirectRoom {
    pub(crate) port: u16,
    /// True when a NAT port mapping was created (UPnP/NAT-PMP/PCP). Always
    /// false in this fatia; the UI warns that the port must be open.
    pub(crate) mapping: bool,
    answers: Arc<Mutex<Vec<PeerSignal>>>,
    shutdown: Arc<AtomicBool>,
    addresses: Arc<Mutex<Vec<DirectAddress>>>,
    _workers: Vec<JoinHandle<()>>,
}

impl DirectRoom {
    pub(crate) fn start(
        mint: OfferMint,
        gate: Arc<SessionGate>,
        viewer_count: ViewerCount,
        host_nickname: String,
    ) -> Result<Self, String> {
        let (listener, ipv6) = bind_direct_listener()?;
        listener
            .set_nonblocking(true)
            .map_err(|error| error.to_string())?;
        let port = listener.local_addr().map_err(|error| error.to_string())?.port();
        let answers = Arc::new(Mutex::new(Vec::new()));
        let shutdown = Arc::new(AtomicBool::new(false));
        let addresses = Arc::new(Mutex::new(Vec::new()));
        let tcp_answers = Arc::clone(&answers);
        let tcp_shutdown = Arc::clone(&shutdown);
        let tcp = thread::Builder::new()
            .name("godrinking-direct-tcp".into())
            .spawn(move || {
                tcp_loop(
                    listener,
                    mint,
                    gate,
                    viewer_count,
                    tcp_answers,
                    tcp_shutdown,
                    host_nickname,
                )
            })
            .map_err(|error| error.to_string())?;
        let addr_answers = Arc::clone(&addresses);
        let addr = thread::Builder::new()
            .name("godrinking-direct-addresses".into())
            .spawn(move || address_worker(port, ipv6, addr_answers))
            .map_err(|error| error.to_string())?;
        Ok(Self {
            port,
            mapping: false,
            answers,
            shutdown,
            addresses,
            _workers: vec![tcp, addr],
        })
    }

    pub(crate) fn take_answers(&self) -> Vec<PeerSignal> {
        self.answers
            .lock()
            .map(|mut answers| std::mem::take(&mut *answers))
            .unwrap_or_default()
    }

    pub(crate) fn addresses(&self) -> Vec<DirectAddress> {
        self.addresses
            .lock()
            .map(|addresses| addresses.clone())
            .unwrap_or_default()
    }
}

impl Drop for DirectRoom {
    fn drop(&mut self) {
        self.shutdown.store(true, Ordering::Release);
    }
}

/// Binds the Direct TCP listener. Prefers a dual-stack `[::]:0` socket (one
/// port for IPv4 and IPv6); falls back to `0.0.0.0:0` when the OS binds
/// `[::]` v6-only (Windows) or the bind fails. Returns whether IPv6 is
/// reachable on the chosen listener.
///
/// On Windows `[::]:0` is v6-only by default (IPV6_V6ONLY=1). We try to
/// create a true dual-stack socket via `socket2` with `only_v6(false)` so
/// one port serves both families and the advertised `[ipv6]:port` is
/// actually reachable. Probe + fallback keeps the old behaviour when that
/// fails.
fn bind_direct_listener() -> Result<(TcpListener, bool), String> {
    // Try a true dual-stack socket first (especially on Windows).
    #[cfg(target_os = "windows")]
    {
        if let Ok(listener) = bind_dual_stack() {
            // Dual-stack succeeded: one port for v4 and v6.
            return Ok((listener, true));
        }
    }
    if let Ok(listener) = TcpListener::bind("[::]:0") {
        let port = listener.local_addr().map_err(|error| error.to_string())?.port();
        // Probe: can IPv4 reach this listener? On Windows `[::]` is v6-only
        // and the probe is refused immediately.
        let ipv4_reachable = TcpStream::connect_timeout(
            &SocketAddr::from(([127, 0, 0, 1], port)),
            Duration::from_millis(150),
        )
        .is_ok();
        if ipv4_reachable {
            logger::log(
                "INFO",
                "direct listen",
                &format!("dual-stack [::]:{port} (v4 reachable)"),
            );
            return Ok((listener, true));
        }
        logger::log(
            "INFO",
            "direct listen",
            &format!("[::]:{port} v6-only, falling back to 0.0.0.0"),
        );
        // Fall through to IPv4-only; the v6-only listener is dropped.
    }
    let listener = TcpListener::bind("0.0.0.0:0").map_err(|error| error.to_string())?;
    logger::log(
        "INFO",
        "direct listen",
        &format!("ipv4-only {}", listener.local_addr().map_err(|e| e.to_string())?),
    );
    Ok((listener, false))
}

#[cfg(target_os = "windows")]
fn bind_dual_stack() -> Result<TcpListener, String> {
    use socket2::{Domain, Protocol, Socket, Type};
    let socket = Socket::new(Domain::IPV6, Type::STREAM, Some(Protocol::TCP))
        .map_err(|e| e.to_string())?;
    socket
        .set_only_v6(false)
        .map_err(|e| e.to_string())?;
    socket
        .set_nonblocking(false)
        .map_err(|e| e.to_string())?;
    let addr: SocketAddr = "[::]:0".parse().map_err(|e: std::net::AddrParseError| e.to_string())?;
    socket
        .bind(&addr.into())
        .map_err(|e| e.to_string())?;
    socket.listen(128).map_err(|e| e.to_string())?;
    let std_listener: std::net::TcpListener = socket.into();
    std_listener
        .set_nonblocking(false)
        .map_err(|e| e.to_string())?;
    Ok(std_listener)
}

/// Collects the copyable Direct addresses on a worker thread so Start never
/// blocks: LAN IPv4 is instant, IPv6 detection is a routing-table lookup, and
/// the STUN binding request is best-effort with a 1.5s timeout. UPnP/NAT-PMP/
/// PCP port mapping is a stub in this fatia (always fails, logged).
fn address_worker(port: u16, ipv6: bool, addresses: Arc<Mutex<Vec<DirectAddress>>>) {
    let mut list = Vec::new();
    for ip in local_addresses() {
        if let Ok(ip) = ip.parse::<IpAddr>() {
            list.push(direct_entry(ip, port, "lan"));
        }
    }
    if ipv6 {
        if let Some(ip) = ipv6_global() {
            list.push(direct_entry(ip, port, "ipv6"));
        }
    }
    if let Ok(mut guard) = addresses.lock() {
        *guard = list.clone();
    }
    if let Some(ip) = stun_public_ipv4() {
        if !list.iter().any(|entry| entry.ip == ip.to_string()) {
            list.push(direct_entry(ip, port, "public"));
        }
        if let Ok(mut guard) = addresses.lock() {
            *guard = list;
        }
    }
    eprintln!(
        "[goDrinking] port mapping failed; Direct over the internet needs this port open"
    );
}

fn direct_entry(ip: IpAddr, port: u16, kind: &str) -> DirectAddress {
    let version = if ip.is_ipv4() { 4 } else { 6 };
    let copy = if ip.is_ipv4() {
        format!("{ip}:{port}")
    } else {
        format!("[{ip}]:{port}")
    };
    DirectAddress {
        ip: ip.to_string(),
        port,
        version,
        kind: kind.into(),
        copy,
    }
}

/// The global IPv6 source address chosen by the routing table, if any.
fn ipv6_global() -> Option<IpAddr> {
    let socket = UdpSocket::bind("[::]:0").ok()?;
    socket.connect("[2600::1]:80").ok()?;
    let ip = socket.local_addr().ok()?.ip();
    match ip {
        IpAddr::V4(v4) if v4.is_loopback() || v4.is_unspecified() => None,
        IpAddr::V6(v6) if v6.is_loopback() || v6.is_unspecified() || v6.is_unicast_link_local() => None,
        _ => Some(ip),
    }
}

/// Best-effort STUN binding request to learn the public IPv4. Never blocks
/// Start: it runs on the address worker with a 1.5s socket timeout.
fn stun_public_ipv4() -> Option<IpAddr> {
    let socket = UdpSocket::bind("0.0.0.0:0").ok()?;
    socket.set_read_timeout(Some(STUN_TIMEOUT)).ok()?;
    let mut request = [0_u8; 20];
    request[0..2].copy_from_slice(&0x0001_u16.to_be_bytes()); // binding request
    request[4..8].copy_from_slice(&0x2112_A442_u32.to_be_bytes()); // magic cookie
    let txid: [u8; 12] = rand::random();
    request[8..20].copy_from_slice(&txid);
    let server = STUN_SERVER.to_socket_addrs().ok()?.next()?;
    socket.send_to(&request, server).ok()?;
    let mut response = [0_u8; 512];
    let (size, _) = socket.recv_from(&mut response).ok()?;
    parse_xor_mapped(&response[..size], &txid)
}

/// Parses the XOR-MAPPED-ADDRESS attribute (0x0020) of a STUN binding
/// success response (0x0101) whose transaction id matches.
fn parse_xor_mapped(response: &[u8], txid: &[u8; 12]) -> Option<IpAddr> {
    if response.len() < 20
        || response[0..2] != 0x0101_u16.to_be_bytes()
        || response[8..20] != *txid
    {
        return None;
    }
    let mut offset = 20;
    while offset + 4 <= response.len() {
        let attr_type = u16::from_be_bytes([response[offset], response[offset + 1]]);
        let attr_len = u16::from_be_bytes([response[offset + 2], response[offset + 3]]) as usize;
        let value_start = offset + 4;
        let value_end = (value_start + attr_len).min(response.len());
        if attr_type == 0x0020 && value_end >= value_start + 8 && response[value_start + 1] == 0x01 {
            let ip = [
                response[value_start + 4] ^ 0x21,
                response[value_start + 5] ^ 0x12,
                response[value_start + 6] ^ 0xA4,
                response[value_start + 7] ^ 0x42,
            ];
            return Some(IpAddr::V4(Ipv4Addr::new(ip[0], ip[1], ip[2], ip[3])));
        }
        offset = value_end + usize::from(attr_len % 4 != 0) * (4 - attr_len % 4);
    }
    None
}

pub(crate) fn random_code() -> String {
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .filter(|byte| byte.is_ascii_alphanumeric() && !byte.is_ascii_lowercase())
        .take(6)
        .map(char::from)
        .collect()
}

fn ice_ip_for_peer(peer: Option<IpAddr>) -> String {
    let Some(ip) = peer else {
        return "127.0.0.1".into();
    };
    let rendered = match ip {
        IpAddr::V4(v4) => v4.to_string(),
        IpAddr::V6(v6) => v6
            .to_ipv4_mapped()
            .map(|v4| v4.to_string())
            .unwrap_or_else(|| v6.to_string()),
    };
    if ip.is_loopback() || local_addresses().iter().any(|local| local == &rendered) {
        return "127.0.0.1".into();
    }
    rendered
}

fn local_addresses() -> Vec<String> {
    let mut addresses = Vec::new();
    if let Ok(socket) = UdpSocket::bind("0.0.0.0:0") {
        let _ = socket.connect("1.1.1.1:80");
        if let Ok(addr) = socket.local_addr() {
            if !addr.ip().is_loopback() {
                addresses.push(addr.ip().to_string());
            }
        }
    }
    if addresses.is_empty() {
        addresses.push("127.0.0.1".into());
    }
    addresses
}

fn tcp_loop(
    listener: TcpListener,
    mint: OfferMint,
    gate: Arc<SessionGate>,
    viewer_count: ViewerCount,
    answers: Arc<Mutex<Vec<PeerSignal>>>,
    shutdown: Arc<AtomicBool>,
    host_nickname: String,
) {
    while !shutdown.load(Ordering::Acquire) {
        match listener.accept() {
            Ok((stream, _)) => {
                let mint = Arc::clone(&mint);
                let gate = Arc::clone(&gate);
                let viewer_count = Arc::clone(&viewer_count);
                let answers = Arc::clone(&answers);
                let host_nickname = host_nickname.clone();
                let _ = thread::Builder::new()
                    .name("godrinking-room-conn".into())
                    .spawn(move || {
                        let _ = handle_tcp(stream, mint, gate, viewer_count, answers, &host_nickname);
                    });
            }
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                thread::sleep(Duration::from_millis(20));
            }
            Err(_) => thread::sleep(Duration::from_millis(50)),
        }
    }
}

/// GOLIVE2 TCP Signaling (PROTOCOL.md section B).
///
/// One TCP per Viewer. The mandatory first line is `HELLO GOLIVE2`; GOLIVE1
/// clients are refused. After `AUTH`/`NICK` the Host either answers
/// `OK <id>` + `OFFER <json>` immediately (Admission off) or `PENDING <id>`
/// and keeps the stream open until the Host decides (Admission on). The
/// Viewer may send `ANSWER <json>` on this same connection after the offer,
/// or on a second connection whose first line is `ANSWER <json>` (the
/// two-step client flow used by the app).
fn handle_tcp(
    mut stream: TcpStream,
    mint: OfferMint,
    gate: Arc<SessionGate>,
    viewer_count: ViewerCount,
    answers: Arc<Mutex<Vec<PeerSignal>>>,
    host_nickname: &str,
) -> Result<(), String> {
    stream
        .set_read_timeout(Some(LINE_TIMEOUT))
        .map_err(|error| error.to_string())?;
    let peer_ip = stream.peer_addr().ok().map(|addr| addr.ip());
    logger::log("INFO", "golive2 conn", &format!("peer={peer_ip:?}"));
    let mut reader = BufReader::new(stream.try_clone().map_err(|error| error.to_string())?);

    let mut first = String::new();
    if reader.read_line(&mut first).map_err(|error| error.to_string())? == 0 {
        return Err("connection closed before HELLO".into());
    }
    let first = first.trim_end();
    // Second-connection ANSWER (Fatia 1 flow): no HELLO/AUTH/NICK needed, the
    // offer id inside the JSON matches the Viewer.
    if let Some(json) = first.strip_prefix("ANSWER ") {
        logger::log("INFO", "golive2 conn", &format!("ANSWER on second connection from {peer_ip:?}"));
        return accept_answer(json, peer_ip, &answers);
    }
    if first != "HELLO GOLIVE2" {
        logger::log("WARN", "golive2 conn", &format!("expected HELLO GOLIVE2, got {first:?}"));
        let _ = stream.write_all(b"ERR PROTO\n");
        return Err("expected HELLO GOLIVE2".into());
    }

    // Ignore list check before AUTH: a banned IP never gets to NICK.
    if let Some(ip) = peer_ip {
        if gate.is_ignored(ip) {
            logger::log("WARN", "golive2 conn", &format!("peer {ip} is on the ignore list; refused"));
            let _ = stream.write_all(b"ERR BANNED\n");
            return Err("peer ip is on the ignore list".into());
        }
    }

    let mut auth_line = String::new();
    if reader.read_line(&mut auth_line).map_err(|error| error.to_string())? == 0 {
        return Err("connection closed before AUTH".into());
    }
    let auth_line = auth_line.trim_end();
    let offered = match auth_line.strip_prefix("AUTH") {
        Some(rest) => rest.strip_prefix(' ').unwrap_or(""),
        None => {
            logger::log("WARN", "golive2 conn", "expected AUTH line");
            let _ = stream.write_all(b"ERR PROTO\n");
            return Err("expected AUTH line".into());
        }
    };
    if !gate.auth_ok(offered) {
        if let Some(ip) = peer_ip {
            gate.note_auth_failure(ip);
        }
        logger::log("WARN", "golive2 conn", &format!("AUTH failed (password mismatch) from {peer_ip:?}"));
        let _ = stream.write_all(b"ERR AUTH\n");
        return Err("password mismatch".into());
    }

    let mut nick_line = String::new();
    if reader.read_line(&mut nick_line).map_err(|error| error.to_string())? == 0 {
        return Err("connection closed before NICK".into());
    }
    let nick_line = nick_line.trim_end();
    let nickname = match nick_line.strip_prefix("NICK ") {
        Some(nickname) => nickname,
        None => {
            logger::log("WARN", "golive2 conn", "expected NICK line");
            let _ = stream.write_all(b"ERR PROTO\n");
            return Err("expected NICK line".into());
        }
    };
    if !valid_nickname(nickname) {
        logger::log("WARN", "golive2 conn", &format!("invalid nickname {nickname:?}"));
        let _ = stream.write_all(b"ERR NICK\n");
        return Err("invalid nickname".into());
    }

    if viewer_count() + gate.pending_roster().len() >= MAX_VIEWERS {
        logger::log("WARN", "golive2 conn", "session is full; ERR FULL");
        let _ = stream.write_all(b"ERR FULL\n");
        return Err("session is full".into());
    }

    let id = random_viewer_id();
    if gate.admission() {
        let rx = gate.register_pending(id.clone(), nickname.to_string());
        logger::log("INFO", "golive2 conn", &format!("PENDING {id} (admission on)"));
        let _ = stream.write_all(format!("PENDING {id}\n").as_bytes());
        if !SessionGate::wait_pending(rx) {
            // Timeout (60s) or Host Reject: remove the slot and tell the
            // Viewer. decide() also removes the slot on timeout.
            gate.decide(&id, false);
            logger::log("INFO", "golive2 conn", &format!("REJECT {id}"));
            let _ = stream.write_all(b"REJECT\n");
            return Ok(());
        }
    }

    let payload = mint(&id, nickname).map_err(|error| {
        logger::log("WARN", "golive2 conn", &format!("mint failed for {id}: {error}"));
        let _ = stream.write_all(b"ERR FULL\n");
        error
    })?;
    let body = serde_json::to_string(&payload).map_err(|error| error.to_string())?;
    logger::log("INFO", "golive2 conn", &format!("OK {id} + OFFER"));
    let _ = stream.write_all(format!("OK {id}\n").as_bytes());
    // The Host's Nickname, so the Viewer can label the Session without
    // showing the raw IP:port. Sent before OFFER; old Viewers skip it.
    if !host_nickname.is_empty() {
        let _ = stream.write_all(format!("HOSTNICK {host_nickname}\n").as_bytes());
    }
    let _ = stream.write_all(format!("OFFER {body}\n").as_bytes());

    // The Viewer may answer on this same connection. If it closed the
    // connection instead (two-step flow), the answer arrives on a second
    // connection and is matched by id.
    stream
        .set_read_timeout(Some(ANSWER_WAIT_TIMEOUT))
        .map_err(|error| error.to_string())?;
    let mut answer_line = String::new();
    if reader.read_line(&mut answer_line).is_ok() {
        let answer_line = answer_line.trim_end();
        if let Some(json) = answer_line.strip_prefix("ANSWER ") {
            logger::log("INFO", "golive2 conn", &format!("ANSWER on first connection from {peer_ip:?}"));
            accept_answer(json, peer_ip, &answers)?;
        }
    }
    Ok(())
}

fn accept_answer(
    json: &str,
    peer_ip: Option<IpAddr>,
    answers: &Arc<Mutex<Vec<PeerSignal>>>,
) -> Result<(), String> {
    let mut signal: PeerSignal =
        serde_json::from_str(json).map_err(|error| error.to_string())?;
    signal.sdp = rewrite_mdns_candidate_addresses(&signal.sdp, &ice_ip_for_peer(peer_ip));
    if let Ok(mut answers) = answers.lock() {
        answers.push(signal);
    }
    Ok(())
}

fn random_viewer_id() -> String {
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .filter(|byte| byte.is_ascii_alphanumeric() && !byte.is_ascii_lowercase())
        .take(8)
        .map(char::from)
        .collect()
}

fn udp_loop(code: Arc<Mutex<String>>, tcp_port: u16, shutdown: Arc<AtomicBool>) {
    let Ok(socket) = UdpSocket::bind(("0.0.0.0", DISCOVERY_PORT)) else {
        return;
    };
    let _ = socket.set_read_timeout(Some(Duration::from_millis(200)));
    let mut buffer = [0_u8; 256];
    while !shutdown.load(Ordering::Acquire) {
        let Ok((size, from)) = socket.recv_from(&mut buffer) else {
            continue;
        };
        let request = String::from_utf8_lossy(&buffer[..size]);
        let current = code.lock().map(|code| code.clone()).unwrap_or_default();
        if let Some(reply) = udp_reply(&request, &current, tcp_port) {
            let _ = socket.send_to(reply.as_bytes(), from);
        }
    }
}

/// Matches a `GOLIVE1 FIND <code>` discovery request against the current
/// Room code. Returns the `GOLIVE1 HOST <code> <port>` reply, or None.
fn udp_reply(request: &str, code: &str, tcp_port: u16) -> Option<String> {
    let mut parts = request.split_whitespace();
    if parts.next() != Some(std::str::from_utf8(DISCOVERY_MAGIC).unwrap_or("GOLIVE1")) {
        return None;
    }
    if parts.next() != Some("FIND") {
        return None;
    }
    if parts.next() != Some(code) {
        return None;
    }
    Some(format!("GOLIVE1 HOST {code} {tcp_port}"))
}

pub fn discover_room(
    code: &str,
    password: &str,
    nickname: &str,
) -> Result<(SocketAddr, PeerSignal, String), String> {
    logger::begin_session("viewer", "lan");
    logger::log("INFO", "lan find", &format!("code={code} nickname={nickname}"));
    let socket = UdpSocket::bind("0.0.0.0:0").map_err(|error| error.to_string())?;
    socket
        .set_broadcast(true)
        .map_err(|error| error.to_string())?;
    socket
        .set_read_timeout(Some(Duration::from_secs(2)))
        .map_err(|error| error.to_string())?;
    let query = format!("GOLIVE1 FIND {code}");
    socket
        .send_to(query.as_bytes(), ("255.255.255.255", DISCOVERY_PORT))
        .map_err(|error| {
            logger::log("ERROR", "lan find", &format!("broadcast failed: {error}"));
            error.to_string()
        })?;
    let mut buffer = [0_u8; 256];
    let (size, from) = socket.recv_from(&mut buffer).map_err(|_| {
        logger::log("ERROR", "lan find", "no host answered (room not found on this network)");
        "room was not found on this network".to_owned()
    })?;
    let reply = String::from_utf8_lossy(&buffer[..size]);
    let mut parts = reply.split_whitespace();
    if parts.next() != Some("GOLIVE1") || parts.next() != Some("HOST") {
        logger::log("ERROR", "lan find", &format!("invalid reply: {reply}"));
        return Err("invalid room discovery reply".into());
    }
    if parts.next() != Some(code) {
        logger::log("ERROR", "lan find", &format!("code mismatch in reply: {reply}"));
        return Err("room code mismatch".into());
    }
    let port = parts
        .next()
        .and_then(|value| value.parse::<u16>().ok())
        .ok_or_else(|| {
            logger::log("ERROR", "lan find", &format!("reply missing port: {reply}"));
            "room reply is missing a port".to_owned()
        })?;
    let host = SocketAddr::new(from.ip(), port);
    logger::log("INFO", "lan find", &format!("host found at {host}"));
    let (offer, host_nickname) = fetch_offer(host, password, nickname)?;
    Ok((host, offer, host_nickname))
}

/// GOLIVE2 Viewer handshake: `HELLO GOLIVE2` / `AUTH` / `NICK`, then wait for
/// `OK`/`PENDING` and finally `OFFER <json>`. With Admission on the Host may
/// keep us waiting up to 60s before deciding; the stream stays open. Returns
/// the offer plus the Host's Nickname (empty when the Host sent none).
pub(crate) fn fetch_offer(
    host: SocketAddr,
    password: &str,
    nickname: &str,
) -> Result<(PeerSignal, String), String> {
    logger::log("INFO", "golive2", &format!("connect {host}"));
    let mut stream = TcpStream::connect_timeout(&host, Duration::from_secs(8))
        .map_err(|error| format!("connect: {error}"))?;
    stream
        .set_read_timeout(Some(PENDING_READ_TIMEOUT))
        .map_err(|error| error.to_string())?;
    stream
        .write_all(b"HELLO GOLIVE2\n")
        .map_err(|error| error.to_string())?;
    if password.is_empty() {
        stream.write_all(b"AUTH\n").map_err(|error| error.to_string())?;
    } else {
        stream
            .write_all(format!("AUTH {password}\n").as_bytes())
            .map_err(|error| error.to_string())?;
    }
    stream
        .write_all(format!("NICK {nickname}\n").as_bytes())
        .map_err(|error| error.to_string())?;
    logger::log("INFO", "golive2", "sent HELLO GOLIVE2 / AUTH / NICK");
    let mut reader = BufReader::new(stream);
    let mut host_nickname = String::new();
    loop {
        let mut line = String::new();
        if reader.read_line(&mut line).map_err(|error| error.to_string())? == 0 {
            logger::log("WARN", "golive2", "host closed the connection");
            return Err("host closed the connection".into());
        }
        let line = line.trim_end();
        if let Some(json) = line.strip_prefix("OFFER ") {
            logger::log("INFO", "golive2", "received OFFER");
            let signal = serde_json::from_str(json).map_err(|error| error.to_string())?;
            return Ok((signal, host_nickname));
        }
        if let Some(name) = line.strip_prefix("HOSTNICK ") {
            host_nickname = name.to_owned();
            continue;
        }
        if line == "REJECT" {
            logger::log("WARN", "golive2", "received REJECT (host declined)");
            return Err("The host declined.".into());
        }
        if line == "PENDING" || line.starts_with("PENDING ") {
            logger::log("INFO", "golive2", "received PENDING (waiting for the host)");
            continue;
        }
        if line == "OK" || line.starts_with("OK ") {
            logger::log("INFO", "golive2", "received OK");
            continue;
        }
        if let Some(error) = line.strip_prefix("ERR ") {
            return Err(protocol_error(error));
        }
    }
}

/// Direct join: no UDP discovery, straight GOLIVE2 TCP to the address the
/// Host shared. TCP failures map to the UI string of UI.md.
pub fn discover_direct(
    host: SocketAddr,
    password: &str,
    nickname: &str,
) -> Result<(PeerSignal, String), String> {
    logger::begin_session("viewer", "direct");
    logger::log("INFO", "direct connect", &format!("host={host} nickname={nickname}"));
    fetch_offer(host, password, nickname).map_err(|error| {
        if error.starts_with("connect: ") {
            logger::log("ERROR", "direct connect", &error);
            "Could not reach that address.".into()
        } else {
            error
        }
    })
}

/// Maps `ERR *` lines to the generic UI strings of UI.md: wrong Password and
/// unknown rooms are indistinguishable, and a banned IP gets the same answer.
/// The raw code is logged so the UI string can be traced.
fn protocol_error(code: &str) -> String {
    logger::log("ERROR", "golive2 err", &format!("ERR {code}"));
    match code {
        "FULL" => "This session is full.".into(),
        _ => "Could not join.".into(),
    }
}

pub fn submit_answer(host: SocketAddr, answer: &PeerSignal) -> Result<(), String> {
    let mut stream = TcpStream::connect_timeout(&host, Duration::from_secs(3))
        .map_err(|error| error.to_string())?;
    let body = serde_json::to_string(answer).map_err(|error| error.to_string())?;
    stream
        .write_all(format!("ANSWER {body}\n").as_bytes())
        .map_err(|error| error.to_string())?;
    stream.shutdown(std::net::Shutdown::Write).ok();
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{handle_tcp, random_code, udp_reply, OfferMint, ViewerCount};
    use crate::media::peer_transport::{PeerSignal, PeerSignalKind};
    use crate::media::session_gate::SessionGate;
    use std::io::{BufRead, BufReader, Write};
    use std::net::{TcpListener, TcpStream};
    use std::sync::{Arc, Mutex};
    use std::time::Duration;

    fn test_mint() -> OfferMint {
        Arc::new(|_id, _nickname| {
            Ok(PeerSignal {
                kind: PeerSignalKind::Offer,
                sdp: "v=0\r\n".into(),
                id: Some("abcd1234".into()),
            })
        })
    }

    fn test_count() -> ViewerCount {
        Arc::new(|| 0)
    }

    #[test]
    fn room_codes_are_short_and_uppercase() {
        let code = random_code();
        assert_eq!(code.len(), 6);
        assert!(code.chars().all(|ch| ch.is_ascii_alphanumeric()));
        assert_eq!(code, code.to_ascii_uppercase());
    }

    #[test]
    fn udp_discovery_answers_only_the_current_code() {
        // Old code stops resolving after a rotate; the new one answers.
        assert_eq!(udp_reply("GOLIVE1 FIND ABC123", "ABC123", 41234).as_deref(),
            Some("GOLIVE1 HOST ABC123 41234"));
        assert_eq!(udp_reply("GOLIVE1 FIND ABC123", "XYZ789", 41234), None);
        assert_eq!(udp_reply("GOLIVE1 FIND XYZ789", "XYZ789", 41234).as_deref(),
            Some("GOLIVE1 HOST XYZ789 41234"));
        assert_eq!(udp_reply("GOLIVE1 FIND ABC123", "ABC123", 41234).as_deref(),
            Some("GOLIVE1 HOST ABC123 41234"));
        // Garbage and wrong magic are ignored.
        assert_eq!(udp_reply("GOLIVE2 FIND ABC123", "ABC123", 41234), None);
        assert_eq!(udp_reply("GOLIVE1 LOOK ABC123", "ABC123", 41234), None);
    }

    #[test]
    fn get_offer_mints_a_fresh_signal() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), false));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server_answers = Arc::clone(&answers);
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(stream, test_mint(), gate, test_count(), server_answers, "Host")
        });
        let mut client = TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH\nNICK Ana\n")
            .expect("write");
        let mut reader = BufReader::new(client.try_clone().expect("clone"));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read ok");
        assert!(line.starts_with("OK "));
        let mut line = String::new();
        loop {
            reader.read_line(&mut line).expect("read offer");
            if line.starts_with("OFFER ") {
                break;
            }
            line.clear();
        }
        assert!(line.contains("abcd1234"));
        // Same-connection ANSWER is accepted and pushed to the answers Vec.
        client
            .write_all(b"ANSWER {\"type\":\"answer\",\"sdp\":\"v=0\\r\\n\",\"id\":\"abcd1234\"}\n")
            .expect("write answer");
        server.join().expect("join").expect("handle");
        let answers = answers.lock().expect("answers");
        assert_eq!(answers.len(), 1);
        assert_eq!(answers[0].id.as_deref(), Some("abcd1234"));
    }

    #[test]
    fn wrong_password_gets_err_auth() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new("secret".into(), false));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(stream, test_mint(), gate, test_count(), answers, "Host")
        });
        let mut client = TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH wrong\nNICK Ana\n")
            .expect("write");
        let mut body = String::new();
        use std::io::Read;
        client.read_to_string(&mut body).expect("read");
        assert!(body.starts_with("ERR AUTH"));
        let _ = server.join().expect("join");
    }

    #[test]
    fn golive1_get_offer_is_refused() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), false));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(stream, test_mint(), gate, test_count(), answers, "Host")
        });
        let mut client = TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client.write_all(b"GET_OFFER\n").expect("write");
        let mut body = String::new();
        use std::io::Read;
        client.read_to_string(&mut body).expect("read");
        assert!(body.starts_with("ERR PROTO"));
        let _ = server.join().expect("join");
    }

    #[test]
    fn admission_pending_then_accept_sends_offer() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), true));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server_gate = Arc::clone(&gate);
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(stream, test_mint(), server_gate, test_count(), answers, "Host")
        });
        let mut client = TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH\nNICK Joao\n")
            .expect("write");
        let mut reader = BufReader::new(client.try_clone().expect("clone"));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read pending");
        let id = line
            .strip_prefix("PENDING ")
            .expect("pending line")
            .trim()
            .to_owned();
        assert!(!id.is_empty());
        // The Host decides from another thread; the pending TCP stays open.
        assert!(gate.decide(&id, true));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read ok");
        assert!(line.starts_with("OK "));
        let mut line = String::new();
        loop {
            reader.read_line(&mut line).expect("read offer");
            if line.starts_with("OFFER ") {
                break;
            }
            line.clear();
        }
        assert!(line.starts_with("OFFER "));
        drop(reader);
        drop(client);
        server.join().expect("join").expect("handle");
    }

    #[test]
    fn admission_reject_closes_with_reject() {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let addr = listener.local_addr().expect("addr");
        let gate = Arc::new(SessionGate::new(String::new(), true));
        let answers = Arc::new(Mutex::new(Vec::new()));
        let server_gate = Arc::clone(&gate);
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            handle_tcp(stream, test_mint(), server_gate, test_count(), answers, "Host")
        });
        let mut client = TcpStream::connect_timeout(&addr, Duration::from_secs(2)).expect("connect");
        client
            .write_all(b"HELLO GOLIVE2\nAUTH\nNICK Joao\n")
            .expect("write");
        let mut reader = BufReader::new(client.try_clone().expect("clone"));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read pending");
        let id = line
            .strip_prefix("PENDING ")
            .expect("pending line")
            .trim()
            .to_owned();
        assert!(gate.decide(&id, false));
        let mut line = String::new();
        reader.read_line(&mut line).expect("read reject");
        assert_eq!(line.trim(), "REJECT");
        drop(reader);
        drop(client);
        server.join().expect("join").expect("handle");
    }

    #[test]
    fn stun_xor_mapped_address_parses() {
        use super::parse_xor_mapped;
        let txid = [7_u8; 12];
        // Binding success header + XOR-MAPPED-ADDRESS for 203.0.113.9:41234.
        let mut response = Vec::new();
        response.extend_from_slice(&0x0101_u16.to_be_bytes());
        response.extend_from_slice(&0x0008_u16.to_be_bytes());
        response.extend_from_slice(&0x2112_A442_u32.to_be_bytes());
        response.extend_from_slice(&txid);
        response.extend_from_slice(&0x0020_u16.to_be_bytes());
        response.extend_from_slice(&0x0008_u16.to_be_bytes());
        response.push(0);
        response.push(0x01); // IPv4 family
        response.extend_from_slice(&(41234_u16 ^ 0x2112).to_be_bytes());
        response.extend_from_slice(&[203 ^ 0x21, 0 ^ 0x12, 113 ^ 0xA4, 9 ^ 0x42]);
        let parsed = parse_xor_mapped(&response, &txid).expect("parses");
        assert_eq!(parsed.to_string(), "203.0.113.9");
        // Wrong transaction id is rejected.
        assert!(parse_xor_mapped(&response, &[1_u8; 12]).is_none());
    }
}
