/** UI copy. Short, in place, no brochure voice. */

export const APP_VERSION = "0.3.0-beta.1";

export const copy = {
  shareNav: "Share screen",
  watchNav: "Watch",
  lanCardTitle: (watching: boolean, live: boolean) =>
    watching ? (live ? "Connected" : "On this network") : live ? "Someone is watching" : "On this network",
  lanCardDetail: (watching: boolean, live: boolean, joinMode: string) => {
    if (joinMode === "stunar") return live ? "P2P. Stunar never sees the video." : "Stunar only introduces you.";
    if (joinMode === "direct") return live ? "P2P to that address." : "They type your IP:port.";
    return watching ? (live ? "Watching the host" : "Same Wi-Fi, a code") : live ? "Sharing is live" : "Same Wi-Fi, a code";
  },
  topSecure: (joinMode: string) =>
    joinMode === "lan" ? "On this network" : "P2P · the server never sees the video",
  shareEyebrow: "Host",
  watchEyebrow: "Watch",
  shareTitle: "Share your screen,",
  shareTitleEm: "stay close.",
  watchTitle: "Enter a code,",
  watchTitleEm: "watch live.",
  sourceKicker: "01 / Source",
  sourceHeading: "Screen or a window",
  wholeScreen: "Whole screen",
  wholeScreenHint: "The monitor, as-is",
  aWindow: "A window",
  aWindowHint: "One app, nothing else",
  nativeSource: "Which one",
  chooseSource: "Pick a source",
  noSources: "No sources yet",
  quality: "Quality",
  qualityLow: "Low",
  qualityMedium: "Medium",
  qualityHigh: "High",
  qualityLine: {
    low: "720p 30 · 1.5 Mbps · H.264. Easy on the network.",
    medium: "1080p 30 · 4 Mbps · H.264.",
    high: "1080p 60 · 8 Mbps · H.264. Ultrawide keeps its shape.",
  } as Record<"low" | "medium" | "high", string>,
  customize: "Customize",
  customizeClosed: "resolution, fps, codec, bitrate",
  resolution: "Resolution cap",
  frameRate: "Frame rate",
  codec: "Codec",
  encoder: "Encoder",
  bitrate: "Target bitrate",
  bitrateHint: "The encoder aims here. It only drops if packets are actually lost.",
  floor: "Floor",
  floorHint: "Won't go below this when the path is losing packets. Auto is ¼ of the target.",
  codecH264: "H.264",
  codecH264High: "H.264 High",
  codecHevc: "HEVC",
  codecAv1: "AV1",
  codecH264Hint: "Works Mac ↔ Windows, GTX 1050 through 40-series, M1+.",
  codecHighHint: "For 1440p/4K. If they stay on Connecting, switch back to H.264.",
  codecHevcHint: "Host is macOS. The other PC needs H.265 decode. ~40% less bitrate.",
  codecAv1Hint: "Best Mac → Mac. Old NVIDIA (10-series) may stutter on decode. Don't pick this for mixed rooms.",
  codecAv1Unavailable: "This PC can't encode AV1.",
  hevcUnavailable: "HEVC encode is macOS-only.",
  encoderAuto: "Auto",
  encoderHw: "Hardware",
  encoderSw: "Software",
  resHint: "Fits inside the cap, keeps the ultrawide ratio, never upscales. Software stays around a 1080p budget; 1440p/4K wants Hardware + H.264 High or HEVC.",
  systemAudio: "Share system audio",
  systemAudioOn: "They hear the PC. Tick apps to keep out of the mix (Discord, etc).",
  systemAudioOff: "Needs macOS 14.2+ or Windows loopback.",
  excludeLabel: "Don't share audio from",
  excludeHint: "They won't hear the apps you pick. Discord is the usual one.",
  excludeHintWin: " Windows can exclude one app per session — first pick wins.",
  nickname: "Nickname",
  joinMode: "How they find you",
  joinLanHost: "Same network. They type your code.",
  joinDirectHost: "They type the IP:port this app shows.",
  joinStunarHost: "Internet. They type your code. Stunar never sees the video.",
  joinLanWatch: "Code from the host on your network.",
  joinDirectWatch: "IP:port the host sent you.",
  joinStunarWatch: "Code from the host. Stunar only introduces you.",
  start: "Start",
  starting: "Starting…",
  stop: "Stop",
  stopping: "Stopping…",
  startHint: "Starting capture…",
  previewKicker: "Preview",
  previewHeading: "What they get",
  previewReady: "Nothing yet",
  previewStart: "Hit Start. The picker comes from the OS.",
  previewNeedPerm: "Turn on Screen Recording for goDrinking, then reopen.",
  previewWinDown: "Capture isn't available on this PC.",
  connectKicker: "02 / Connect",
  passCode: "Pass this code",
  shareAddress: "Share this address",
  incomingKicker: "Preview",
  incomingHeading: "Their screen",
  joinKicker: "01 / Join",
  joinHeadingCode: "Session code",
  joinHeadingDirect: "Host address",
  joinSession: "Join",
  joining: "Joining…",
  permissionChecking: "Checking capture…",
  permissionReady: "Capture ready",
  permissionWinReady: "Windows capture ready",
  permissionNeeded: "Screen Recording is off",
  permissionUnavailable: "Capture unavailable",
  statsHostHint: "This is the encoder target. Their Status shows what actually arrived. A drop here means packet loss, not the slider lying.",
  statsViewerHint: (preset: string, mbps: number) =>
    `If this sits far below the host target (${preset}: ${mbps} Mbps) and the picture blocks, the path is losing packets.`,
  sessionMode: "Session",
  broadcast: "Broadcast",
  room: "Sala",
  broadcastHint: "You share. They watch. That's it.",
  roomHint: "Open the room without sharing. Anyone can send a screen; you pick who to receive.",
  shareMine: "Share my screen",
  stopShareMine: "Stop sharing",
  openRoom: "Open room",
  leaveRoom: "Leave room",
  closeRoom: "Close room",
  watchPerson: "Watch",
  unwatchPerson: "Stop",
  pinTile: "Pin",
  unpinTile: "Unpin",
  shareWarn: "More than 4 screens at once will hurt. Keep it small.",
  measurePc: "Measure this PC",
  measureHint: "Local encoder probe. Nothing goes on the network.",
} as const;
