/** UI copy. English and Brazilian Portuguese. Short, in place. */

export const APP_VERSION = "0.5.0";

export type Locale = "en" | "pt-BR";

const en = {
  shareNav: "Share screen",
  watchNav: "Watch",
  lanCardTitle: (watching: boolean, live: boolean): string =>
    watching ? (live ? "Connected" : "On this network") : live ? "Someone is watching" : "On this network",
  lanCardDetail: (watching: boolean, live: boolean, joinMode: string): string => {
    if (joinMode === "stunar") return live ? "P2P. Stunar never sees the video." : "Stunar only introduces you.";
    if (joinMode === "direct") return live ? "P2P to that address." : "They type your IP:port.";
    return watching ? (live ? "Watching the host" : "Same Wi-Fi, a code") : live ? "Sharing is live" : "Same Wi-Fi, a code";
  },
  topSecure: (joinMode: string): string =>
    joinMode === "lan" ? "On this network" : "P2P · the server never sees the video",
  shareEyebrow: "Host",
  watchEyebrow: "Watch",
  shareTitle: "Share your screen,",
  shareTitleEm: "keep it close.",
  watchTitle: "Got a code?",
  watchTitleEm: "jump in.",
  sourceKicker: "01 / Source",
  sourceHeading: "Screen or a window",
  wholeScreen: "Whole screen",
  wholeScreenHint: "The monitor, as-is",
  aWindow: "A window",
  aWindowHint: "One app, nothing else",
  nativeSource: "Which one",
  chooseSource: "Pick a source",
  noSources: "No sources yet",
  quality: "Quality",
  qualityLow: "Low",
  qualityMedium: "Medium",
  qualityHigh: "High",
  qualityLine: {
    low: "720p 30 · 1.5 Mbps · H.264. Easy on the network.",
    medium: "1080p 30 · 4 Mbps · H.264.",
    high: "1080p 60 · 8 Mbps · H.264. Ultrawide keeps its shape.",
  } as Record<"low" | "medium" | "high", string>,
  customize: "Customize",
  customizeClosed: "resolution, fps, codec, bitrate",
  resolution: "Resolution cap",
  frameRate: "Frame rate",
  codec: "Codec",
  encoder: "Encoder",
  bitrate: "Target bitrate",
  bitrateHint: "The encoder aims here. It only drops if packets are actually lost.",
  floor: "Floor",
  floorHint: "Won't go below this when the path is losing packets. Auto is 1/4 of the target.",
  codecH264: "H.264",
  codecH264High: "H.264 High",
  codecHevc: "HEVC",
  codecAv1: "AV1",
  codecH264Hint: "Works Mac to Windows, GTX 1050 through 40-series, M1+.",
  codecHighHint: "For 1440p/4K. If they stay on Connecting, switch back to H.264.",
  codecHevcHint: "Host is macOS. The other PC needs H.265 decode. About 40% less bitrate.",
  codecAv1Hint: "Best Mac to Mac. Older NVIDIA 10-series cards may stutter on decode. Skip this in mixed rooms.",
  codecAv1Unavailable: "This PC can't encode AV1.",
  hevcUnavailable: "HEVC encode is macOS-only.",
  encoderAuto: "Auto",
  encoderHw: "Hardware",
  encoderSw: "Software",
  resHint: "Fits inside the cap, keeps the ultrawide ratio, never upscales. Software stays around a 1080p budget; 1440p/4K wants Hardware + H.264 High or HEVC.",
  systemAudio: "Share system audio",
  systemAudioOn: "They hear the PC. Tick apps to keep out of the mix (Discord, etc).",
  systemAudioOff: "Needs macOS 14.2+ or Windows loopback.",
  excludeLabel: "Don't share audio from",
  excludeHint: "They won't hear the apps you pick. Discord is the usual one.",
  excludeHintWin: " Windows can exclude one app per session; first pick wins.",
  nickname: "Nickname",
  joinMode: "How they find you",
  joinLanHost: "Same network. They type your code.",
  joinDirectHost: "They type the IP:port this app shows.",
  joinStunarHost: "Internet. They type your code. Stunar never sees the video.",
  joinLanWatch: "Code from the host on your network.",
  joinDirectWatch: "IP:port the host sent you.",
  joinStunarWatch: "Code from the host. Stunar only introduces you.",
  start: "Start",
  starting: "Starting…",
  stop: "Stop",
  stopping: "Stopping…",
  startHint: "Starting capture…",
  previewKicker: "Preview",
  previewHeading: "What they get",
  previewReady: "Nothing yet",
  previewStart: "Hit Start. The OS picker comes up next.",
  previewNeedPerm: "Turn on Screen Recording for goDrinking, then reopen.",
  previewWinDown: "Capture isn't available on this PC.",
  connectKicker: "02 / Connect",
  passCode: "Pass this code",
  shareAddress: "Share this address",
  incomingKicker: "Preview",
  incomingHeading: "Their screen",
  joinKicker: "01 / Join",
  joinHeadingCode: "Session code",
  joinHeadingDirect: "Host address",
  joinSession: "Join",
  joining: "Joining…",
  permissionChecking: "Checking capture…",
  permissionReady: "Capture ready",
  permissionWinReady: "Windows capture ready",
  permissionNeeded: "Screen Recording is off",
  permissionUnavailable: "Capture unavailable",
  statsHostHint: "This is the encoder target. Their Status shows what actually arrived. If this number drops, packets are getting lost.",
  statsViewerHint: (preset: string, mbps: number): string =>
    `If this sits far below the host target (${preset}: ${mbps} Mbps) and the picture blocks, the path is losing packets.`,
  sessionMode: "Session",
  broadcast: "Broadcast",
  room: "Room",
  broadcastHint: "You share. They watch. That's it.",
  roomHint: "Opens on the stage. Settings is one click away.",
  shareMine: "Share my screen",
  stopShareMine: "Stop sharing",
  openRoom: "Open room",
  leaveRoom: "Leave room",
  closeRoom: "Close room",
  backToRoom: "Back to the room",
  roomSettings: "Settings",
  watchPerson: "Watch",
  unwatchPerson: "Stop",
  pinTile: "Pin",
  unpinTile: "Unpin",
  shareWarn: "More than 4 screens at once will hurt. Keep it small.",
  measurePc: "Measure this PC",
  measureHint: "Local encoder probe. Nothing goes on the network.",
  leave: "Leave",
  videoOnly: "Video only",
  videoOnlyExit: "Exit",
  muted: "Muted",
  volume: "Vol",
  streamStatus: "Stream status",
  nobodyOnScreen: "Nobody on screen",
  nobodyOnScreenHint: "Watch someone who is sharing. Empty tiles stay off the grid.",
  inTheRoom: "In the room",
  you: "You",
  sharingYou: "Sharing · you",
  onlyYou: "You're the only one here for now.",
  sharing: "Sharing",
  liveWatching: "Live · watching",
  inRoom: "In the room",
  collecting: "Collecting…",
  yourEncoder: "Your encoder. Open Status in Settings for the full readout.",
  noPeerYet: "No peer yet.",
  workspace: "Workspace",
  language: "Language",
};

export type Copy = typeof en;

const ptBR: Copy = {
  shareNav: "Compartilhar",
  watchNav: "Assistir",
  lanCardTitle: (watching: boolean, live: boolean): string =>
    watching ? (live ? "Conectado" : "Nesta rede") : live ? "Alguém está assistindo" : "Nesta rede",
  lanCardDetail: (watching: boolean, live: boolean, joinMode: string): string => {
    if (joinMode === "stunar") return live ? "P2P. O Stunar não vê o vídeo." : "O Stunar só apresenta vocês.";
    if (joinMode === "direct") return live ? "P2P para esse endereço." : "Eles digitam seu IP:porta.";
    return watching ? (live ? "Assistindo o host" : "Mesmo Wi-Fi, um código") : live ? "Compartilhamento no ar" : "Mesmo Wi-Fi, um código";
  },
  topSecure: (joinMode: string): string =>
    joinMode === "lan" ? "Nesta rede" : "P2P · o servidor não vê o vídeo",
  shareEyebrow: "Host",
  watchEyebrow: "Assistir",
  shareTitle: "Compartilhe a tela,",
  shareTitleEm: "fica perto.",
  watchTitle: "Tem um código?",
  watchTitleEm: "entra.",
  sourceKicker: "01 / Fonte",
  sourceHeading: "Tela ou janela",
  wholeScreen: "Tela inteira",
  wholeScreenHint: "O monitor, do jeito que está",
  aWindow: "Uma janela",
  aWindowHint: "Um app, mais nada",
  nativeSource: "Qual",
  chooseSource: "Escolhe a fonte",
  noSources: "Nenhuma fonte ainda",
  quality: "Qualidade",
  qualityLow: "Baixa",
  qualityMedium: "Média",
  qualityHigh: "Alta",
  qualityLine: {
    low: "720p 30 · 1.5 Mbps · H.264. Leve na rede.",
    medium: "1080p 30 · 4 Mbps · H.264.",
    high: "1080p 60 · 8 Mbps · H.264. Ultrawide mantém o formato.",
  },
  customize: "Ajustar",
  customizeClosed: "resolução, fps, codec, bitrate",
  resolution: "Teto de resolução",
  frameRate: "Quadros",
  codec: "Codec",
  encoder: "Encoder",
  bitrate: "Bitrate alvo",
  bitrateHint: "O encoder mira aqui. Só cai se estiver perdendo pacote de verdade.",
  floor: "Piso",
  floorHint: "Não desce disso quando a rede está perdendo pacote. Auto é 1/4 do alvo.",
  codecH264: "H.264",
  codecH264High: "H.264 High",
  codecHevc: "HEVC",
  codecAv1: "AV1",
  codecH264Hint: "Mac e Windows, GTX 1050 até 40-series, M1+.",
  codecHighHint: "Para 1440p/4K. Se ficar em Connecting, volta para H.264.",
  codecHevcHint: "Host no macOS. O outro PC precisa decodificar H.265. Uns 40% menos bitrate.",
  codecAv1Hint: "Melhor de Mac para Mac. NVIDIA 10-series antiga pode engasgar no decode. Evita em sala mista.",
  codecAv1Unavailable: "Este PC não encoda AV1.",
  hevcUnavailable: "HEVC encode só no macOS.",
  encoderAuto: "Auto",
  encoderHw: "Hardware",
  encoderSw: "Software",
  resHint: "Cabe no teto, mantém o ultrawide, nunca aumenta. Software fica perto de um orçamento 1080p; 1440p/4K pede Hardware + H.264 High ou HEVC.",
  systemAudio: "Compartilhar áudio do sistema",
  systemAudioOn: "Eles ouvem o PC. Marca apps para tirar da mix (Discord, etc).",
  systemAudioOff: "Precisa de macOS 14.2+ ou loopback no Windows.",
  excludeLabel: "Não compartilhar áudio de",
  excludeHint: "Eles não ouvem os apps que você marcar. Discord é o de sempre.",
  excludeHintWin: " No Windows dá para excluir um app por sessão; o primeiro vale.",
  nickname: "Apelido",
  joinMode: "Como te acham",
  joinLanHost: "Mesma rede. Eles digitam seu código.",
  joinDirectHost: "Eles digitam o IP:porta que o app mostra.",
  joinStunarHost: "Internet. Eles digitam seu código. O Stunar não vê o vídeo.",
  joinLanWatch: "Código do host na sua rede.",
  joinDirectWatch: "IP:porta que o host te mandou.",
  joinStunarWatch: "Código do host. O Stunar só apresenta vocês.",
  start: "Começar",
  starting: "Começando…",
  stop: "Parar",
  stopping: "Parando…",
  startHint: "Abrindo a captura…",
  previewKicker: "Preview",
  previewHeading: "O que eles veem",
  previewReady: "Nada ainda",
  previewStart: "Aperta Começar. O seletor do sistema aparece.",
  previewNeedPerm: "Liga a Gravação de Tela para o goDrinking e abre de novo.",
  previewWinDown: "Captura não está disponível neste PC.",
  connectKicker: "02 / Conectar",
  passCode: "Passa este código",
  shareAddress: "Passa este endereço",
  incomingKicker: "Preview",
  incomingHeading: "A tela deles",
  joinKicker: "01 / Entrar",
  joinHeadingCode: "Código da sessão",
  joinHeadingDirect: "Endereço do host",
  joinSession: "Entrar",
  joining: "Entrando…",
  permissionChecking: "Checando captura…",
  permissionReady: "Captura pronta",
  permissionWinReady: "Captura Windows pronta",
  permissionNeeded: "Gravação de Tela está desligada",
  permissionUnavailable: "Captura indisponível",
  statsHostHint: "Este é o alvo do encoder. O Status deles mostra o que chegou. Se este número cair, está perdendo pacote.",
  statsViewerHint: (preset: string, mbps: number): string =>
    `Se ficar bem abaixo do alvo do host (${preset}: ${mbps} Mbps) e a imagem bloquear, o caminho está perdendo pacote.`,
  sessionMode: "Sessão",
  broadcast: "Broadcast",
  room: "Sala",
  broadcastHint: "Você compartilha. Eles assistem. Pronto.",
  roomHint: "Abre no palco. Ajustes ficam a um clique.",
  shareMine: "Compartilhar minha tela",
  stopShareMine: "Parar de compartilhar",
  openRoom: "Abrir sala",
  leaveRoom: "Sair da sala",
  closeRoom: "Encerrar sala",
  backToRoom: "Voltar para a sala",
  roomSettings: "Ajustes",
  watchPerson: "Assistir",
  unwatchPerson: "Parar",
  pinTile: "Fixar",
  unpinTile: "Soltar",
  shareWarn: "Mais de 4 telas ao mesmo tempo aperta. Fica pequeno.",
  measurePc: "Medir este PC",
  measureHint: "Sonda local do encoder. Nada vai para a rede.",
  leave: "Sair",
  videoOnly: "Só vídeo",
  videoOnlyExit: "Sair",
  muted: "Mudo",
  volume: "Vol",
  streamStatus: "Status da stream",
  nobodyOnScreen: "Ninguém na tela",
  nobodyOnScreenHint: "Assiste alguém que está compartilhando. Tile vazio não entra na grade.",
  inTheRoom: "Na sala",
  you: "Você",
  sharingYou: "Compartilhando · você",
  onlyYou: "Por enquanto é só você aqui.",
  sharing: "Compartilhando",
  liveWatching: "Ao vivo · assistindo",
  inRoom: "Na sala",
  collecting: "Coletando…",
  yourEncoder: "Seu encoder. Abre Status em Ajustes para o relatório completo.",
  noPeerYet: "Ainda sem peer.",
  workspace: "Espaço",
  language: "Idioma",
};

export const dictionaries: Record<Locale, Copy> = { en, "pt-BR": ptBR };
export const copy = en;

export function detectLocale(): Locale {
  try {
    const saved = localStorage.getItem("godrinking.locale");
    if (saved === "en" || saved === "pt-BR") return saved;
  } catch { /* ignore */ }
  try {
    if (typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("pt")) return "pt-BR";
  } catch { /* ignore */ }
  return "en";
}
